### ISSUE TITLE
Beloved --recommended flag

### ISSUE THREAD

**Issue by BFergerson** [src-d/engine#105]
Would be nice to see this in the srcd engine considering it's in Babelfish.

Desired command: `srcd parse drivers install --recommended`

Actual output:
```
Error: unknown flag: --recommended
Usage:
  srcd parse drivers install [flags]

Flags:
  -h, --help   help for install

Global Flags:
      --config string   config file (default is $HOME/.srcd.yaml)
  -v, --verbose         if true, log all of the things

unknown flag: --recommended
```

**Comment by BFergerson** [comment]
Just noticed the `-all` and `-alpha` options. Guessing there will also be `-beta`/`-stable` etc.

Those would also solve this issue but don't seem to be implemented yet.

**Comment by smacker** [comment]
Hi @BFergerson when you run any command that requires bblfsh for more than 1 language (like `sql` or `web uast`) engine installs `recommended` drivers for your. You most probably don't need to manage them manually. There is even an issue with proposal to remove it: https://github.com/src-d/engine/issues/85

**Comment by carlosms** [comment]
I'm closing this since now we are including the recommended drivers pre-installed on the bblfsh image we use.
