### ISSUE TITLE
Spark: investigate a suspicious warning

### ISSUE THREAD

**Issue by bzz** [src-d/engine#120]
On running over `./examples/siva-files`

```
make clean build
SPARK_HOME="" ./spark/bin/spark-shell --jars ./target/scala-2.11/engine-uber.jar
```

```scala
val engine = Engine(spark, "./examples/siva-files")

engine.getRepositories.getHEAD.getFiles.classifyLanguages.where('lang === "Python").extractUASTs.queryUAST("//*[@roleIdentifier]", "uast", "result").extractTokens("result", "tokens").select('path, 'lang, 'uast, 'tokens).show
```

results in suspicious warning

```
17/10/18 18:25:01 WARN Executor: Managed memory leak detected; size = 4456448 bytes, TID = 1034
```

**Comment by ajnavarro** [comment]
Some related issues:
https://issues.apache.org/jira/browse/SPARK-18784
https://issues.apache.org/jira/browse/SPARK-18181
https://issues.apache.org/jira/browse/SPARK-14168

**Comment by ajnavarro** [comment]
Interesting comment too: https://issues.apache.org/jira/browse/SPARK-18181?focusedCommentId=15816160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15816160

> I'm pretty sure this is just a misleading msg, not a true leak. Any time a task fails, you'll see that msg about any of the memory that is currently used by the task. It looks like in your case, you're just triggering an OOM in your code.
