### ISSUE TITLE
Include Flag to Paginate SQL Query Output

### ISSUE THREAD

**Issue by ricardobaeta** [src-d/engine#122]
I would be pretty happy if there was a way to "paginate" query results. The results could be divided in ~50 lines blocks, and I would have the chance to "navigate" up and down (with index 1 of 5...). It could be as of a flag that would be included on the cli output when running **srcd sql --help**. It would look something like:

```
Run a SQL query over the analyzed repositories.

Usage:
  srcd sql [flags]

Flags:
  -h, --help   help for sql
  -p, --p paginate query results

Global Flags:
      --config string   config file (default is $HOME/.srcd.yaml)
  -v, --verbose         if true, log all of the things
```

> We have pagination on the web sql and I believe that being on the cli shouldn't degrade this specific usability detail

**Comment by smola** [comment]
@ajnavarro Transferred to engine.

**Comment by carlosms** [comment]
I don't know if this should be part of the `srcd` command, when adding pagination in the CLI is already solved with the `more` or `less` tools.
e.g. `srcd sql "select * from commits;" | less`

**Comment by smacker** [comment]
I believe the feature request is for interactive mode:

```
$ srcd sql
> select * from commits;
<no pagination here>
```

**Comment by carlosms** [comment]
related to #154, this could be solved by replacing our sql client.

**Comment by smacker** [comment]
It was fixed by using the standard mysql client. Not exactly as described in the issue description but in the way familiar to anybody who has experience with cli utils for databases.
