### ISSUE TITLE
Cleanup components list

### ISSUE THREAD

**Issue by jfontan** [src-d/engine#124]
In a development machine the list of components is huge. I expect it to be only the containers that are supposed to run:

```
$ srcd components list
bblfsh/bblfshd:latest
srcd/gitbase:dev-e063e33c-dirty
srcd/gitbase:dev-81616185-dirty
srcd/gitbase:v0.17.0-rc.3
srcd/cli-daemon:latest
srcd/gitbase-web:latest
srcd/borges:dev-0190fa5-dirty
srcd/borges:dev-db200e8-dirty
srcd/borges:latest
srcd/regression-gitbase:dev-e7eb027-dirty
srcd/regression-gitbase:dev-aadb5ed-dirty
srcd/regression-borges:latest
srcd/regression-gitbase:dev-e8ac494-dirty
srcd/regression-gitbase:dev-3c87f93-dirty
srcd/engine-jupyter:dev-c9815bc-dirty
srcd/engine-jupyter:dev-95ab85c-dirty
srcd/jupyter-spark:5.2.1
srcd/jupyter-spark:latest
srcd/engine-jupyter:dev-795d4ac-dirty
srcd/engine-installer:latest
srcd/engine-jupyter:latest
bblfsh/bblfshd:v2.2.0
srcd/engine-jupyter:dev-47c7bc7-dirty
bblfsh/bblfshd:v2.1.2
bblfsh/bblfshd:v2.0.0
```

Version: 0.1.8

**Comment by smola** [comment]
I think unknown images (`srcd/regression-gitbase`, `srcd/engine-jupyter`) should not appear at all.
With respect versions, I think it would make sense to show only those that are known to the current src-d/engine version by default, then add a flag `--all`, `-a` to include other versions that exist locally, to ease trying development versions or newer/older ones.
