### ISSUE TITLE
Rename head_ref to head, master_ref to master

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#126]
I do understand that this has smth to do with the Scala API, but Python users should not suffer because of the name collision in the different language. `references.head_ref` is a duplication.

**Comment by erizocosmico** [comment]
[`DataFrame` has a method `head`](http://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrame.head) in Python as well, that's why we can't name it `head`.

**Comment by vmarkovtsev** [comment]
While I have no better suggestions, it still sucks

**Comment by erizocosmico** [comment]
We just can't do anything to rename it to `head`, `head` is a `DataFrame` method. If you have any suggestion about the renaming of this in the future, please reopen the issue.
