### ISSUE TITLE
Gitbase index persistence and pilosa

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#13]
Gitbase indexes should be persisted in a volume somewhere. 

We could have a shared folder, like `~/.srcd` where we can store drivers and indexes, so they can be mounted in the containers

Ideally, `~/.srcd/gitbase/WORKDIR/PATH`, so every time you start gitbase with a different path the indexes are not mixed up

Should we also start a pilosa server? We have pilosalib now, which doesn't require it, but don't know how stable that is or if it's on master. Gotta check it

**Comment by eiso** [comment]
+1 on this idea. I think it's still recommended to use the pilosa server and we can switch it to lib in the next release.

@kuba-- or can we go directly to lib?

**Comment by kuba--** [comment]
Yep, I think it's pretty stable (I tried to fix all bugs and inconsistency recently). It's on master and I didn't encounter any issues for last week, or so.
Moreover, personally I'd like to get rid of old pilosa driver  (unless someone sees benefits having indexes on external http server).

Current folders structure looks like this: 
https://github.com/src-d/go-mysql-server/pull/308#issuecomment-409583989

That's all what we need.

**Comment by eiso** [comment]
@kuba-- see my comment on the latest leads meeting minutes about the pilosa server driver.

Sounds like we don't need to launch a pilosa server, great!

**Comment by kuba--** [comment]
@eiso - you mean this comment: https://github.com/src-d/minutes/pull/312#discussion_r211934168

The only benefit which I see right now is clustering/sharding. If we gonna have distributed DB then would be good to have distributed index as well (instead of sync up all indexes across all db instances)

**Comment by eiso** [comment]
This is a worthwhile discussion to have but rather do it when @smola and @mcuadros are back from holiday on Monday. @kuba-- can you raise it in Slack then.

**Comment by kuba--** [comment]
sure thing!

**Comment by erizocosmico** [comment]
I will start a pilosa container too so we have both options.

**Comment by kuba--** [comment]
The only thing which we have to have in the back of our mind is pilosa server version. We still uses v0.9.0 but they've already release v1.0.X
So if we wanna keep it, then some day we'll have to upgrade, what we'll require a little bit refactoring because they changed API.
