### ISSUE TITLE
Make release process more automatic

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#146]
Right now, to release a new version we need: 

- Change the project version on build.sbt
- Push changes to master
- Create tag pointing to that commit
- Push to master moving the version to the next `-SNAPSHOT` one

Use some plugin to automate this process.

**Comment by ajnavarro** [comment]
Some solutions: https://github.com/sbt/sbt-release

**Comment by ajnavarro** [comment]
I found a more straight forward way to do releases as we are used to (creating tags on git): 

https://github.com/scalacenter/sbt-release-early

Should we try it?

**Comment by ajnavarro** [comment]
sbt-release-early is only compatible with scala 2.10 or 2.12

**Comment by erizocosmico** [comment]
Should we upgrade to scala 2.12, then?

**Comment by ajnavarro** [comment]
we cannot, Spark only supports 2.10 and 2.11 :sob:
