### ISSUE TITLE
Optimize Joins also if a Limit is on the LogicalPlan

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#156]
Right now we only support Projects and Filters between the Join and the GitRelation. We should support Limit too.

**Comment by ajnavarro** [comment]
Also we can do another rule to pushdown limits to GitRelations. Doing this we can leave the Join pushdown rule as it is, encapsulating the functionality.

**Comment by erizocosmico** [comment]
We can do the optimization if Limit's child is directly the GitRelation, if it's a filter we can't do it right now. Not unless we got rid of the filter nodes and just filter ourselves everything inside the GitRelation.

So, this would be optimized

```
engine.repositories.references.limit(2).commits
```

But not this

```
engine.repositories.references.where("some filter").limit(2).commits
```

**Comment by erizocosmico** [comment]
I'm gonna move this to blocked until @ajnavarro returns and see if we can come up with something.

**Comment by erizocosmico** [comment]
Shall we close this? As we discussed IRL there is no way to fix this with chained iterators, as putting the limit in another place changes the meaning of the query.
