### ISSUE TITLE
Quick-start in Readme, wrong download filename

### ISSUE THREAD

**Issue by zurk** [src-d/engine#157]
When I run this command on ubuntu 16.04, as described in readme
```bash
wget "https://www.apache.org/dyn/mirrors/mirrors.cgi?action=download&filename=spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz"
```
I have a file named
```
mirrors.cgi?action=download&filename=spark%2Fspark-2.2.0%2Fspark-2.2.0-bin-hadoop2.7.tgz
```

but not `spark-2.2.0-bin-hadoop2.7.tgz` as you expect in next step.
```
tar -xzf spark-2.2.0-bin-hadoop2.7.tgz; cd spark-2.2.0-bin-hadoop2.7
```

It is minor issue, but better to correct instructions.

**Comment by mcarmonaa** [comment]
Thanks for reporting @zurk! This PR #158 should fix it.

**Comment by zurk** [comment]
Ok, it solved. I close the issue.
