### ISSUE TITLE
Cannot bootstrap gitbase web client due to GH's api rate limit

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#160]
Occasionally the gitbase web client cannot be bootstrapped due to exceeding the Github's api rate limit.

Here's the error message that occurred the first time I tried to run it:

    ✔  se7entyse7en in ~/Projects/src-d/engine (master)  $ srcd web sql                                                                                                              [12/17/18 | 16:41:18.255]
    INFO[0003] this is taking a while, if this is the first time you launch this web client, it might take a few more minutes while we install all the required images 
    INFO[0003] installing \"bblfsh/bblfshd:v2.10.0-drivers\" 
    INFO[0089] installed \"bblfsh/bblfshd:v2.10.0-drivers\" 
    INFO[0089] starting bblfshd daemon                      
    INFO[0102] installing all recommended drivers           
    FATA[0103] could not start gitbase web client at port 8080: rpc error: code = Unknown desc = could not create srcd-cli-bblfshd: GET https://api.github.com/orgs/bblfsh/repos?page=1&per_page=100&type=public: 403 API rate limit exceeded for 83.55.53.42. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) [rate reset in 7m16s]

**Comment by smacker** [comment]
As we discussed in slack one of the possible solutions would be to disable drivers discovery in engine completely by using only drivers installed in `-drivers` images or hard-code versions on our side.
