### ISSUE TITLE
Instruction how to launch engine from python

### ISSUE THREAD

**Issue by EgorBu** [src-d/engine#160]
Hi,
I could launch engine with help of @ajnavarro but it's not so obvious.
We had to copy `engine.jar` to `pyspark/jars`.
I think it's not the best way (ultrahardcode), if you know better way - I will be glad to use it.
After copying you can create engine with:
```python
import sys

pyspark_path = "/path/to/pyspark/python"
sys.path.append(pyspark_path)

from bblfsh import BblfshClient, filter
from pyspark.sql import SparkSession
from sourced.engine import Engine

siva_folder = "/path/to/siva-files"
spark = SparkSession.builder.appName("test").master("local[*]").getOrCreate()
engine = Engine(spark, siva_folder)
```

**Comment by ajnavarro** [comment]
Some related links: https://blog.sicara.com/get-started-pyspark-jupyter-guide-tutorial-ae2fe84f594f

**Comment by erizocosmico** [comment]
Will be taken care of by #162

**Comment by zurk** [comment]
Also, I think that It is a good idea to put some comments into readme.

**Comment by erizocosmico** [comment]
@zurk yes, #162 will take care of that.
