### ISSUE TITLE
Better error message if jar is not loaded and update docs

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#162]
- When jar is not loaded, Py4J throws an exception like `TypeError: 'JavaPackage' object is not callable`, we should catch that exception and throw another saying that `jar` with engine is not loaded and available in the JVM
- Update README so it reflects that jar has to be manually loaded when using PySpark

**Comment by erizocosmico** [comment]
https://github.com/src-d/engine/pull/163 tackles the first part

**Comment by erizocosmico** [comment]
@EgorBu did you try with `SPARK_SUBMIT_ARGS`? (from outside, not from `os.environ`)

**Comment by EgorBu** [comment]
@erizocosmico , no, what should I put there? I can check it right now

**Comment by erizocosmico** [comment]
@EgorBu https://github.com/jupyter/docker-stacks/wiki/Docker-recipes#using-local-spark-jars

**Comment by EgorBu** [comment]
@erizocosmico , thanks, it works!
