### ISSUE TITLE
Return already converted Rows (a.k.a. RDD[InternalRow]) instead of standard Rows to improve speed performance.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#182]
On `BaseRelation` class we have:

```
  /**
   * Whether does it need to convert the objects in Row to internal representation, for example:
   *  java.lang.String to UTF8String
   *  java.lang.Decimal to Decimal
   *
   * If `needConversion` is `false`, buildScan() should return an `RDD` of `InternalRow`
   *
   * @note The internal representation is not stable across releases and thus data sources outside
   * of Spark SQL should leave this as true.
   *
   * @since 1.4.0
   */
  def needConversion: Boolean = true
```

we should override it to false, and change the output of CatalystScan from `RDD[Row]` to `RDD[InternalRow]`, changing all the generated row types to the converted types (per example, Date rows are Integers in InternalRows).

**Comment by erizocosmico** [comment]
Should we really do this considering the `@note`? How much of a performance gain is there with this?

**Comment by ajnavarro** [comment]
1.- Regarding the @note , we are already using a lot of APIs that are not stable, like the `CatalystScan`
2.- We don't know the improvement, if any.

**Comment by ajnavarro** [comment]
Is actually slower: https://github.com/src-d/engine/pull/213
