### ISSUE TITLE
Docs. How to define the images? Can we use HTML?

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#185]
Caused by https://github.com/src-d/engine/pull/183

We realized that if an image is enclosed by an html tag, it is not displayed in GitBook.

In that case, it was used a `<p>` to center the enclosed image;
if we remove the html parent tag, we need to agree on the following:

- do we want to find another way to center an image?
- do we want to resize images using `<img src=URL width=SIZE />`?
- do we want to forbid any kind of `html` in our docs, and use only `markdown`?

**Comment by dpordomingo** [comment]
I wonder whether we @src-d/applications can decide on our own (as project maintainers), or we should raise this issue as a company-wide one considering an alternative owner of the source{d} documentation.

/cc @smola

**Comment by Rajakavitha1** [comment]
I suggest that we first draft a style guide for the documentation that outlines the guidelines for word usage and formatting text. This ensures consistency. Also it might a good idea to consider a separate folder for images and SVG format for the web so that all the images in the documents are in one consolidated location.( Easy to maintain and edit).

**Comment by dpordomingo** [comment]
I like your suggestions;
About moving the images into a separate folder, it seems reasonable and it's something that we somehow did in `lookout` (we moved that stuff into `docs/assets` dir, [see](https://github.com/src-d/lookout/tree/master/docs/assets)).
But the purpose of this issue is to raise the problem to a higher level, to help decision makers to clarify whether it should be decided by the maintainer of the project, or it should be a company-wide rule.
We'll post here the news about it so all external contributor will be benefited with more clear guidelines.

**Comment by smola** [comment]
@dpordomingo 

> I wonder whether we @src-d/applications can decide on our own (as project maintainers)

Yes, you decide. Feel free to ask if you want any feedback to choose a solution, but it's up to you.

**Comment by carlosms** [comment]
@dpordomingo can we close this one?

**Comment by dpordomingo** [comment]
Did we agree with something about it?

If the following suits you, we can close this with as a conclusion; otherwise we should consider it as an open discussion.

- no html in docs with the purpose of formating content
  - no centered images in docs
  - images can be defined with HTML in order to define sizing `<img src=URL width=SIZE />`
