### ISSUE TITLE
Logrus colors in windows are broken

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#187]
When working on #45 I noticed that the colors of the logs written with logrus are not rendered correctly on Windows (I tried Windows 10).
 
<img width="1008" alt="screenshot 2019-01-03 at 15 09 01" src="https://user-images.githubusercontent.com/5599208/50641920-d28dc580-0f69-11e9-877f-7e213c30b483.png">

By doing a quick search I found that [this commit](https://github.com/sirupsen/logrus/commit/bb98c6c5333eab6d403627978bbde01d60f176a7) in logrus should fix the coloring on windows and it is available in `v1.2.0`. Nevertheless there's also [this PR](https://github.com/sirupsen/logrus/pull/864) that has not been released yet, but that disables text colouring for Windows completely.

Here are other [related PRs](https://github.com/sirupsen/logrus/pulls?utf8=%E2%9C%93&q=is%3Apr+windows).

Maybe we could wait for the next release of logrus and update the dependency.

**Comment by smacker** [comment]
we are using v1.4.0 now and this was fixed.
