### ISSUE TITLE
Token extraction for all revisions of the single project never finishes

### ISSUE THREAD

**Issue by bzz** [src-d/engine#196]
While building an application using Engine, I want to extract all the tokens from Python files and get back the result as `(repository, file, [tokens])`

Here is what I did
```sh
# with latest bbflshd container running
# with Borges 0.8.3
# with Apache Spark 2.2.0 installed in $SPARK_HOME

echo -e "https://github.com/src-d/borges.git\nhttps://github.com/erizocosmico/borges.git\nhttps://github.com/jelmer/dulwich.git" > repos.txt
borges pack --loglevel=debug --workers=2 --to=./repos -f repos.txt

$SPARK_HOME/bin/spark-shell --driver-memory=4g --packages "tech.sourced:engine:0.1.7"
```

and run

```scala
import tech.sourced.engine._

val engine = Engine(spark, "repos")
val repos = engine.getRepositories
val refs = repos.getHEAD.withColumnRenamed("hash","commit_hash")

val langs = refs.getCommits.getFirstReferenceCommit.getFiles.classifyLanguages
val pyTokens = langs
  .where('lang === "Python")
  .extractUASTs.queryUAST("//*[@roleIdentifier]", "uast", "result")
  .extractTokens("result", "tokens")

val tokensToWrite = pyTokens
  .join(refs, "commit_hash")
  .select('repository_id, 'name, 'commit_hash, 'file_hash, 'path, 'lang, 'tokens)

spark.conf.set("spark.sql.shuffle.partitions", "30") //instead of default 200
tokensToWrite.show
```

After 30 min, non of the jobs were finished and in `Executor->Thread Dump` one can see all workers threads in `BblfshClient`.
 
May be there is a better way of archiving the same, any feedback is highly appreciated.

**Comment by bzz** [comment]
`pyTokens.show` though work as expected, producing an output quiet fast.

**Comment by bzz** [comment]
`pyTokens.show` finishes in 2min though

**Comment by bzz** [comment]
Initial code snippet in description was extracting tokens for every file in _every revision_ 

> val langs = refs.getFiles.classifyLanguages

instead of

```scala
val langs = refs.getCommits.getFirstReferenceCommit.getFiles.classifyLanguages
```

This mistake is very easy to make and may be quite hard to notice.

**Comment by erizocosmico** [comment]
Perhaps we should document that "if you don't use `getFirstReferenceCommit` you're probably gonna need a lifespan extension to get your results" message or something. We're redoing the files table iterator right now, so it _may_ be a little better in the end, but can't make promises yet.

Anyway, did using `getFirstReferenceCommit` solve your issue? If it did, this becomes a docs issue, otherwise it's a bug.

**Comment by bzz** [comment]
Single commit for 1 project works now!

Agreed, better doc is always good. 

Do you think `refs.getFiles` is generally something anybody may be interested in getting at this point?

**Comment by bzz** [comment]
Sorry if I have missed it, but how #204 addresses the use-case discussed here?

AFAIK `.getFiles()` still might be called on all references un-intentionally by the user.

Just FYI - the same anti-pattern is followed in https://github.com/src-d/engine/blob/master/_examples/scala/spark-shell-schemas.md

**Comment by erizocosmico** [comment]
I was under the impression all we agreed to do was document the `getFirstReferenceCommit` preference. Ok, I will make the default behavior of getFiles for references get the first commit only.

**Comment by bzz** [comment]
👍 I think that would be a good default from performance point of view!
