### ISSUE TITLE
[feature-request] Return python object instead of java in parse_uast_node method in python wrapper

### ISSUE THREAD

**Issue by zurk** [src-d/engine#198]
Engine has a parse_uast_node method (https://github.com/src-d/engine/blob/master/python/sourced/engine/engine.py#L87). But it returns a Java object now.

This method can be in demand and helpful.

For now one can use: 
```python
def process_uast(uast_bytes):
    from bblfsh.sdkversion import VERSION
    uast_tree = importlib.import_module(
            "bblfsh.gopkg.in.bblfsh.sdk.%s.uast.generated_pb2" % VERSION)\
            .Node.FromString(uast_bytes)
    # Do what you need with uast_tree
```
inside `select` method for Spark DataFrame.

**Comment by erizocosmico** [comment]
@ajnavarro this requires adding client-python as a dependency, which requires `libxml-dev` installed and some other C++ mumbo jumbo. Worth making the entry barrier higher for this feature?

**Comment by erizocosmico** [comment]
For now, we have decided not to include this feature in the python bindings, as this makes `bblfsh` python package needed in the engine python bindings and it would require `libxml-dev` installed and building the native extension and so on.

If you need some kind of UDF to deal with the UASTs, though, feel free to propose it so you don't end up needing to decode the protobuf at all.

**Comment by zurk** [comment]
it is always task-specific UDF and they are needed only for one machine learning model.
For example, this method https://github.com/src-d/ml/blob/master/ast2vec/repo2/coocc.md where we have tricky UAST tree processing. I don't think it is a good idea to include it in the engine. 

Maybe it is time for @src-d/machine-learning team to learn Scala? :)

**Comment by vmarkovtsev** [comment]
Over my dead body.

**Comment by erizocosmico** [comment]
You can still use [this](https://github.com/src-d/engine/issues/198#issue-274807941) snippet. It's just too little a benefit to include it in the bindings taking into account all it requires.
