### ISSUE TITLE
Logo requested

### ISSUE THREAD

**Issue by eiso** [src-d/engine#2]
Since the source{d} engine is the packaging of our projects as a product, it should have a logo.

**Comment by ricardobaeta** [comment]
Sure thing Eiso, I'll articulate with @marnovo the timings on this.

**Comment by campoy** [comment]
It'd be sad to launch without a logo, and @marnovo is on holidays.

Even if it's something temporary, do you think you could come up with something for tomorrow, @ricardobaeta ?

**Comment by carlosms** [comment]
Closing, rationale in the related product repo: the [text logo](https://github.com/src-d/lookout/blob/master/docs/assets/sourced-lookout.png) with the new brand style already counts as the project logo.
