### ISSUE TITLE
Release: include Scala version in published Jar artifact name

### ISSUE THREAD

**Issue by bzz** [src-d/engine#208]
Engine is an awesome Scala/Python library that is intended to be used as a dependency in number of applications.

Typical Scala application built with `sbt` would depend on engine by `"tech.sourced" %% "engine" % "0.1.8"` but that would fail the build 

```
[warn] 	Note: Unresolved dependencies path:
[warn] 		tech.sourced:engine_2.11:0.1.8
sbt.ResolveException: unresolved dependency: tech.sourced#engine_2.11;0.1.8: not found
``` 

As the intended use case for a published jar is to be consumed by Scala applications, it would make sense to include Scala version in the published artefact name.

**Comment by ajnavarro** [comment]
Actually you can add the dependency dropping one of the `%`: ` "tech.sourced" % "engine" % "0.1.8"`. Actually is only compatible with scala 2.11.x

**Comment by erizocosmico** [comment]
Is this solved, then?

**Comment by ajnavarro** [comment]
No, we should check if we are adding to the dependency pom dependencies that we already have shaded on the jar. I think this is what is causing the error.

**Comment by ajnavarro** [comment]
we can say yes, but we should put on the library requisites that the engine only works with scala 2.11.x

**Comment by erizocosmico** [comment]
Will add it to the `README.md`, then.

**Comment by bzz** [comment]
> Actually is only compatible with scala 2.11.x,

Sorry if I have missed the explanation, but is there a technical reason for that?

**Comment by ajnavarro** [comment]
Basically, Spark: https://spark.apache.org/docs/2.2.0/#downloading
