### ISSUE TITLE
Unable to finish/very slow query on OSX for "big" repos/collections of repos

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#208]
When working on [this](https://github.com/src-d/engine/issues/196) I was not able to run the following query using the web interface:
```
    SELECT * FROM (
        SELECT cf.file_path,
               UAST(f.blob_content, LANGUAGE(f.file_path,  f.blob_content)) as uast
        FROM ref_commits r 
        NATURAL JOIN commit_files cf 
        NATURAL JOIN files f 
        WHERE r.ref_name = 'HEAD' 
        AND r.history_index = 0
    ) t WHERE uast != '';
```

Here's some context:
- https://github.com/src-d/engine/issues/196#issuecomment-459096463
- https://github.com/src-d/engine/issues/196#issuecomment-462340189

Could be related to [this](https://github.com/src-d/engine/issues/156).

**Comment by se7entyse7en** [comment]
Initially I thought that the query was not finishing and that something was hanging. But when I was inspecting the resource consumption while the query was running, after 693s the query finished and the result was shown on the web interface. `engine` was initialized using the `spark` repo as workdir.

**Comment by se7entyse7en** [comment]
Running the same query with both `gitbase` and `gitbase-web` running natively took ~9s 😕. So that's clearly something that it's not working as expected or that has be tuned when running on docker.

**Comment by smacker** [comment]
@se7entyse7en be aware of this: https://github.com/src-d/engine/issues/156
afaik you are using mac so it should affect you

**Comment by se7entyse7en** [comment]
@smacker yup I'm aware of that issue. I'm just wondering whether it is expected to be THAT slow. Given that you're also using OSX could you try running this query on engine? I also gathered the resources usage stats and after the query I also have gitbase-web using +6GiB of memory, gitbase +3GiB. Maybe this is just expected.

**Comment by se7entyse7en** [comment]
Here's the report of resources usage during the query:
[query_stats_01.txt](https://github.com/src-d/engine/files/2856236/query_stats_01.txt)

**Comment by se7entyse7en** [comment]
Okay, when `gitbase` and `gitbase-web` are running natively the same query actually took the same amount of time (same order of magnitude). So it's not an `engine` issue.
