### ISSUE TITLE
Release: make it possible to build fat jar with Engine as dependency

### ISSUE THREAD

**Issue by bzz** [src-d/engine#210]
When building an application with Engine as a dependency, building fat jar fails presumably due to duplication of dependencies in Engine:
 -  they are declared in `pom.xml`
 - they are included in `engine-uber.jar`

So an application that depends on engine, while building a fat jat gets both copies - one from transitive dependencies declaration and another from .jar

```
[error] deduplicate: different file contents found in the following:
[error] ~/.ivy2/cache/tech.sourced/engine/jars/engine-0.1.8.jar:tech/sourced/siva/Index.class
[error] ~/.ivy2/cache/tech.sourced/siva-java/jars/siva-java-0.1.1.jar:tech/sourced/siva/Index.class
[error] deduplicate: different file contents found in the following:
[error] ~/.ivy2/cache/tech.sourced/engine/jars/engine-0.1.8.jar:tech/sourced/siva/IndexEntry.class
[error] ~/.ivy2/cache/tech.sourced/siva-java/jars/siva-java-0.1.1.jar:tech/sourced/siva/IndexEntry.class
[error] deduplicate: different file contents found in the following:
[error] ~/.ivy2/cache/tech.sourced/engine/jars/engine-0.1.8.jar:tech/sourced/siva/IndexFooter.class
[error] ~/.ivy2/cache/tech.sourced/siva-java/jars/siva-java-0.1.1.jar:tech/sourced/siva/IndexFooter.class
[error] deduplicate: different file contents found in the following:
```

**Comment by erizocosmico** [comment]
How are you building the project? I can't reproduce this.

I created a new empty project with the following `build.sbt`

```scala
organization := "foo.yadayada"
scalaVersion := "2.11.11"
version := "1.0.0"
name := "yadayada"

libraryDependencies += "tech.sourced" % "engine" % "0.1.8" % Compile
```

Ran `sbt package` and it succeeded.

Can you provide reproducible steps for this issue? Thanks.

**Comment by ajnavarro** [comment]
the problem is when you try to create a uber-jar of your project I think.

**Comment by erizocosmico** [comment]
let me check

**Comment by bzz** [comment]
Yes, exactly.

To simplify Engine consumption for the applications (who will be building their own fatJars), it would be really nice to:
 - reshade everything inside `engine-uber.jar` (and not only grpc)
 - remove all included dependency declaration from published `pom.xml`

Publishing thing jar would make less sense, as although as flexible as it is (allows consumers to override everything), that would require them to build fat jar anyway + re-shade at least GRPC to make it all usable in Apache Spark.

**Comment by erizocosmico** [comment]
Remove all included dependencies from `pom.xml` does nothing.

The solution seems to be reshading all. I'm currently doing that, but I believe it's not going to work, because we even have to reshade scala. So instead of passing a `scala.collection.immutable.Map` you might have to pass a `shadedscala.collection.immutable.Map` which is worse for the user.

**Comment by bzz** [comment]
> Remove all included dependencies from pom.xml does nothing.

I'm not sure I understand it right, from what I see - only doing that would solve the issue reported.

Main issue is inability to build fatJar for the artefact that depends on Engine. Presumably due to build system being confused by having 2 copy of dependencies - inside the engine-uber.jar and from transitive dependency resolution.

Re-sharing everything (well, may be scala can be declared as Provided and be left out of uber.jar?) is nice bonus just to avoid possible runtime classname collision.

**Comment by erizocosmico** [comment]
I just tried without these dependencies in pom.xml and can confirm it does not work.

**Comment by erizocosmico** [comment]
Managed to get it to work by tweaking a bit the `ivy.xml` generated.

**Comment by bzz** [comment]
@erizocosmico I'm sorry, but as of 0.1.10 it does not work for me again :/

My previous tests work due to having jgit in provided scope, relying on engine fatJar to bring it, before the selective reshading. But now jgit dependency have to be declared as `compile` (as only jgit, but not it's transitive dependencies, are reshaded) and building application fatJar does not work for me again, failing with the same symptoms  :/

Here is the example https://github.com/bzz/srcd-engine-app

```
git clone https://github.com/bzz/srcd-engine-app.git
cd srcd-engine-app
./sbt assembly
```
