### ISSUE TITLE
SQL connection retries with annoying messages

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#211]
If the SQL connection is not ready the DB is pinged every second and on each retry a log message from the server is printed. With multiple retries this is annoying such in the following screenshot:

<img width="1440" alt="screenshot 2019-02-11 at 23 22 28" src="https://user-images.githubusercontent.com/5599208/52597716-00610680-2e54-11e9-9079-9c6c02fa5194.png">

Here are some suggestions on how this could be approached:
- https://github.com/src-d/engine/pull/195#issuecomment-462441673
- https://github.com/src-d/engine/pull/195#pullrequestreview-202315124

**Comment by dpordomingo** [comment]
I'd only log:
`\ Waiting for gitbase to be ready`
^ with an spinner

question.
When gitbase container is starting it logs valuable info to the user; can't we display it?
```
time="2019-02-12T18:55:42Z" level=debug msg="repository added" path=/opt/repos/blog
time="2019-02-12T18:55:42Z" level=debug msg="repository added" path=/opt/repos/borges
time="2019-02-12T18:55:42Z" level=debug msg="repository added" path=/opt/repos/charts
time="2019-02-12T18:55:42Z" level=debug msg="repository added" path=/opt/repos/ci
time="2019-02-12T18:55:42Z" level=debug msg="repository added" path=/opt/repos/engine
...
time="2019-02-12T18:55:42Z" level=error msg="repository could not be added" error="the repository is already registered: /opt/repos/docs-sources/engine" id=engine path=/opt/repos/engine
...
time="2019-02-12T18:53:08Z" level=debug msg="registered database to catalog" db=gitbase
time="2019-02-12T18:53:08Z" level=debug msg="registered all available functions in catalog"
time="2019-02-12T18:53:08Z" level=debug msg="created index storage"
time="2019-02-12T18:53:08Z" level=debug msg="registered pilosa index driver"
time="2019-02-12T18:53:08Z" level=info msg="squash tables rule is enabled"
time="2019-02-12T18:53:08Z" level=info msg="server started and listening on 0.0.0.0:3306"
```

That way the user will know:
- something is happening in the background,
- which repos are being added,
- some repos could not being added,
- index and some rules were enabled,
- finaly the server is listening under certain port.

**Comment by se7entyse7en** [comment]
@dpordomingo I also think that some of these informations could be valuable for the user. I don't know if the user is interested in all of them. For example I don't know if the user is interested in knowing the gitbase is running on `0.0.0.0:3306`, but I agree that some informations regarding the repose added are certainly valuable.

Just a question, do you have any idea on how to distinguish the messages to propagate except from using a regex to match the messages we're interested? The log level doesn't seem to be discriminating.

**Comment by smacker** [comment]
The current function that redirects logs from a container is very stupid and redirect everything as a text. Reasoning is described in pr: https://github.com/src-d/engine/pull/109 (tl;dr we didn't need make it more smart)

**Comment by se7entyse7en** [comment]
Regarding the spinner thing. I've implemented a function to do that, but I was thinking that if we write also something else on the console it would be difficult to rewrite the line with the spinner.

In our case if we print:
```
\ Waiting for gitbase to be ready
```

using a spinner, but while the spinner is going we also want to log something else, I don't know if there's some clever solution except from rewriting each line after the `\ Waiting for gitbase to be ready` message.

**Comment by carlosms** [comment]
My opinion is that we could do a simple improvement now with the spinner (or even add dots for each connection attempt `Waiting for gitbase to be ready .......`).
And then consider the logs a different feature request. Maybe the logs make sense as a new command, similar to `docker-compose logs`.

**Comment by smacker** [comment]
@se7entyse7en Maybe there is a lib for a spinner that can also handle other messages correctly? So we don't need to reinvent the wheel.

**Comment by se7entyse7en** [comment]
> And then consider the logs a different feature request.

I agree, I'm gonna open a new issue then to address the inclusion/different handling of the logs.

> Maybe there is a lib for a spinner that can also handle other messages correctly?

Yup, initially I didn't want to include a lib just for a simple spinner. Anyway not needed anymore for this issue.

**Comment by dpordomingo** [comment]
I'm not sure if spinner + logs are needed.
if logs are appended, the spinner is going to disappear at some point, so...
I'd do as @carlosms suggested https://github.com/src-d/engine/issues/211#issuecomment-463283865
- spinner (or appended dots),
- and then replace with proper logs.

**Comment by se7entyse7en** [comment]
@dpordomingo I don't know if I understood correctly what you meant.
Currently as in the GIF the behaviour is:
- log `Waiting for gitbase to be ready \`, where the last character is the spinner,
- when it ends replace `Waiting for gitbase to be ready \` with `Waiting for gitbase to be ready, done`, or `Waiting for gitbase to be ready, error: <err>` depending on the response.

If I understood correctly what you mean, this should be:
- log `Waiting for gitbase to be ready`,
- on new line write a spinner or appended dots,
- when it ends replace the line with the spinner/appended dots with proper logs.

**Comment by dpordomingo** [comment]
my suggestion would be:
```shell
$ srcd sql "select * from repositories"
starting daemon with working dir ~
this is taking a while, if this is the first...
startin bblfshd daemon

/ waiting for gitbase to be ready
```
^ only a spinner until gitbase is ready; no a new `connecting to mysql...` every second.

Once we're able to print `srcd-cli-gitbase` logs (because it is implemented by this issue, or because it is postponed to the future as @carlosms suggested), the spinner is no longer needed, and we can replace it with printing the logs as they come from the container.

**Comment by se7entyse7en** [comment]
> ^ only a spinner until gitbase is ready; no a new `connecting to mysql...` every second.

Isn't it already achieved [here](https://github.com/src-d/engine/pull/216)? Specifically in the 3rd and 4th case. It doesn't log `connecting to mysql...` anymore and it doesn't print the logs from the container too until we figure out how to handle them.
