### ISSUE TITLE
engine usage leads to docker break (MacOS)

### ISSUE THREAD

**Issue by zurk** [src-d/engine#211]
I have the problem that I can reproduce only on MacOS. 

Here is step by step instruction to reproduce it.
1. Run docker and bblfsh `docker run -d --rm --name bblfshd --privileged -p 9432:9432 bblfsh/bblfshd:v2.1.2 --log-level debug; docker exec -it bblfshd bblfshctl driver install --all`. The same result for last bblfsh v2.2.0.
2. Run `jupyter notebook`. It is not necessary. You can achieve the same result with just python code.
3. Run first 4 cells from my [notebook](https://gist.github.com/zurk/faaa4187f542f4b4b1a2c9af476e276f). Don't forget to change the path to Siva files and download `token_parser.py` file.

you will get next output: 
https://gist.github.com/zurk/0792c132c7b6c07170f2ac0981ee86c7

Note that it does not happen on Ubuntu.
4. And the last one. Try to `docker ps`. It will give you `Error response from daemon: Bad response from Docker engine`. Now you need to restart docker.

I do not know why and what really happen, also it can be related to babelfish itself. 

And I find docker issue, about such behavior but without any useful details. 
https://github.com/docker/for-mac/issues/2056
https://github.com/docker/for-mac/issues/2042

PS: I will try to make my python example shorter for you.

**Comment by campoy** [comment]
Hi @zurk,

I'm trying to reproduce the bug but I'm not sure what to do on step 2.
Once the drivers have been installed on the bblfshd container you run jupyter from it? do you run it on your host machine and somehow connect it to the engine?

Could you give more details to see whether I'm able to reproduce?

Thanks

**Comment by smacker** [comment]
Can't reproduce. I do have similar traceback, but containers are okay.

MacOs High Sierra 10.13.1
bblfshd 2.2.0
srcd/engine 0.1.8

**Comment by zurk** [comment]
hey, guys, @campoy, @smacker here is smaller code to reproduce:
```python
from operator import add

from sourced.engine import Engine
from pyspark.sql import SparkSession
from pyspark.sql.functions import size, col, log
spark = SparkSession.builder.master("local[*]").appName("Examples").getOrCreate()

# use files from example: https://github.com/src-d/engine/tree/master/examples/siva-files
engine = Engine(spark, "./engine/examples/siva-files/")

def get_all_files():
    frc = engine.repositories.filter("is_fork = false").references.head_ref.commits.first_reference_commit
    return frc.files.join(frc.select("repository_id", col("hash").alias("commit_hash")), "commit_hash")

def get_tokens(uasts):
    return uasts.query_uast('//*[@roleIdentifier and not(@roleIncomplete)]').extract_tokens().where(size(col("tokens")) != 0)

# here I able to get output
uasts = get_all_files().extract_uasts().select("path", "uast", col("commit_hash").alias("document"))
tokens = get_tokens(uasts)
tokens.show()

# and one more time, now have error
uasts = get_all_files().extract_uasts().select("path", "uast", col("commit_hash").alias("document"))
tokens = get_tokens(uasts)
tokens.show()
```

About 2nd step from the first message. 
> do you run it on your host machine and somehow connect it to the engine?

I just run it on my local machine. Connect it to the engine via first commands in python.
```
spark = SparkSession.builder.master("local[*]").appName("Examples").getOrCreate()
engine = Engine(spark, "./engine/examples/siva-files/")
```
the same way as in engine example (https://github.com/src-d/engine/blob/master/examples/notebooks/Example.ipynb). 

Same about this smaller code example. I run it locally.

Versions: 

bblfshd 2.1.2
srcd/engine 0.1.8
docker: Version 17.09.0-ce-mac35 (19611)
MacOS: 10.13.1 (17B48)

**Comment by smacker** [comment]
@zurk still everything works fine: https://gist.github.com/smacker/087de271378bfc7ee4c24c48277ab90f

**Comment by zurk** [comment]
ok, interesting. 
I do a little bit different.

1. Use Python3 in PySpark. You should set next environment vars on Mac. 
```
PYSPARK_PYTHON=python3
PYSPARK_PYTHON_DRIVER=python3
```


2. And also I do not close python interpreter. I run `docker ps` in another terminal. When I try to do like you I get the same result. Here is my output https://gist.github.com/zurk/699805ac0c4bb231cb5f9d067af90d2b

**Comment by smacker** [comment]
nope. Python3 and everything works fine.
It's very weird to run `docker ps` in another terminal, because if daemon died - you will see it from anywhere. Anyway, I tried. Works fine for me.

**Comment by zurk** [comment]
@smacker it did not die actually, more likely it does not respond until you close your python session. And the point is not about another terminal, but just run the command (`docker ps`) before you close python.

That exactly what you do and it did not work, did it?

**Comment by smacker** [comment]
I did everything exactly as you explained and `docker ps` works fine.
```
$ docker -v
Docker version 17.09.0-ce, build afdb6d4
```

**Comment by zurk** [comment]
ok, now I am in trouble. :) Will try to reinstall everything.

**Comment by erizocosmico** [comment]
It seems to not be related to the engine, so I will close the issue. Feel free to reopen if you find that it's somehow related later on.

**Comment by zurk** [comment]
Now I can explain few more things. 
It was the same problem as described here: https://github.com/bblfsh/python-driver/issues/140 but for some reason, it also breaks my docker.
Since I use engine v0.2.0, I don't have any problems like this.
