### ISSUE TITLE
Stopping underlying containers sometimes takes longer than timeout

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#213]
Sometimes a `context deadline exceeded` is raised when a container is being stopped. But sometimes it takes much longer than the timeout. Maybe we should address this by increasing the timeout or by understanding why in some cases it take so much time or by thinking other possible solutions.

Here's a screen:

<img width="1440" alt="screenshot 2019-02-12 at 12 03 04" src="https://user-images.githubusercontent.com/5599208/52631099-2e7b3080-2ebe-11e9-90d1-2951d2b0a481.png">

In this specific case `gitbase-web` was using +6GiB of memory, that could be the reason.

**Comment by se7entyse7en** [comment]
I have multiple ideas on how to approach this:
1. increase the timeout:
  - very simple to do
  - if the timeout expires, the next call to stop will continue to print `removal already in progress` without actually waiting
2. check for the `removal already in progress` and state polling:
  - it doesn't exit immediately, but what I'd do is to start polling for the container state
  - the same timeout still applies
3. check for the `removal already in progress` and use `ContainerWait`*:
  - with `ContainerWait` we can wait until the container is not running anymore instead of polling its state
  - I actually don't know how it behaves given that we're force removing the container, but maybe we could split kill and removal and also use different timeouts
4. check for the `removal already in progress` and use `ContainerWait` with api version >= 1.30:
  - with api version >= 1.30 we could use `ContainerWait` and wait until the container is not removed

*[link](https://godoc.org/github.com/docker/docker/client#Client.ContainerWait) to `ContainerWait`

The cleanest solution I think is 4., but it requires updating from 1.13 to 1.30 and I don't know if there are breaking changes. I found [this](https://docs.docker.com/engine/api/version-history/) but there's no clear statement about breaking changes and also it starts from 1.18. And taken from [here](https://docs.docker.com/develop/sdk/#versioned-api-and-sdk):

> A given version of the Docker Engine SDK supports a specific version of the Docker Engine API, as well as all earlier versions. If breaking changes occur, they are documented prominently.

**Comment by carlosms** [comment]
2, 3 and 4 change how it works _if_ you try to run `stop` a second time, but they don't solve the first `context deadline exceeded` response right?

Instead of 4, waiting indefinitely for the container to be stopped the second time you run `stop`. Is it not better to wait the first `stop`, removing the context deadline or setting it for a few minutes?

**Comment by se7entyse7en** [comment]
> 2, 3 and 4 change how it works _if_ you try to run `stop` a second time, but they don't solve the first `context deadline exceeded` response right?

yup, correct.

> Instead of 4, waiting indefinitely for the container to be stopped the second time you run `stop`. Is it not better to wait the first `stop`, removing the context deadline or setting it for a few minutes?

I'd rather not remove the context deadline but better increase it to few minutes as you said (currently it's 30s). But in the case that the time is still not enough, and a `context deadline exceeded` is not enough, what do you propose to do?

The simplest solution would be to completely remove the timeout, and then the user will eventually stop the operation. But even in this case if the user stops the operation and retries it, I think that the docker is still in "removing/stopping" state, so even in this case engine will raise a `removal already in progress` error.

**Comment by se7entyse7en** [comment]
What I mean is that IMO in any case we need to handle the case when the removal is already in progress by trying to wait the end of it. The problem is how we wanna implement it.

**Comment by carlosms** [comment]
I think we could fix the `context deadline exceeded` error now with a higher timeout of a few minutes.

And then open a new issue for "what happens when `srcd stop` is called and the removal is already in progress"; and @src-d/product can decide how it should behave (exit/waiting).

**Comment by se7entyse7en** [comment]
Ok! I agree, asking for @src-d/product is the best option! Thanks! Later I'm gonna open the issue 👍

**Comment by smacker** [comment]
btw when you do `docker stop` it doesn't have a timeout at all. I had some weird cases when it was stopping container for dozen of minutes and docker didn't complain.
