### ISSUE TITLE
"exit" on srcd sql doesn't exit command prompt

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/engine#215]
When using gitbase, I run the docker container and mysql client. On this case, when I'm inside mysql and type `exit`, it exits the command prompt.

However, when using the engine, typing "exit" jumps to a new line on the prompt.

Only when I type `exit;` with the semicolon it exits.

Although it's not a bug, I would expect to have the same experience with the engine and the standard mysql client.

**Comment by carlosms** [comment]
> Although it's not a bug, I would expect to have the same experience with the engine and the standard mysql client.

One more argument to replace our REPL with a mysql client, as suggested in #154.

**Comment by carlosms** [comment]
Fixed in #353.
