### ISSUE TITLE
Use case comparison: source{d} engine vs. Boa language

### ISSUE THREAD

**Issue by marnovo** [src-d/engine#218]
The [following examples](http://boa.cs.iastate.edu/examples/) are achievable through the [Boa language](http://boa.cs.iastate.edu/index.php) for "Mining Ultra-Large-Scale Software Repositories" of the Iowa State University. It seems the Boa language is so far possibly the closest to a "competitor" the engine has at this point.

It is a good idea to see which ones we can reproduce using source{d} engine queries (and make these into our example list) and which ones we cannot—and if we want these to be future features of the engine.

Their example list with the corresponding code [can be found here](http://boa.cs.iastate.edu/examples/index.php) and is listed again below:

- [x] **1. Programming Languages**
    - [x] 1.What are the ten most used programming languages?
    - [x] 2. How many projects use more than one programming language?
    - [x] 3. How many projects use the Scheme programming language?
- [x] **2. Project Management**
    - [x] 1. How many projects are created each year?
    - [ ] 2. How many projects self-classify into each topic provided by SourceForge?
    - [x] 3. How many Java projects using SVN were active in 2011?
    - [x] 4. In which year was SVN added to Java projects the most?
    - [x] 5. How many revisions are there in all Java projects using SVN?
    - [x] 6. How many revisions fix bugs in all Java projects using SVN?
    - [x] 7. How many committers are there for each project?
    - [ ] 8. What are the churn rates for all projects?
    - [x] 9. How did the number of commits for Java projects using SVN change over years?
    - [x] 10. How often are popular Java build systems used?
- [x] **3. Legal**
    - [x] 1. What are the five most used licenses?
    - [x] 2. How many projects use more than one license?
- [x] **4. Platform/Environment**
    - [ ] 1. What are the five most supported operating systems?
    - [ ] 2. Which projects support multiple operating systems?
    - [x] 3. What are the five most popular databases?
    - [x] 4. What are the projects that support multiple databases?
    - [x] 5. How often is each database used in each programming language?
- [x] **5. Source Code**
    - [x] 1. What are the five largest projects, in terms of AST nodes?
    - [x] 2. How many valid Java files in latest snapshot?
    - [ ] 3. How many fixing revisions added null checks?
    - [ ] 4. What files have unreachable statements?
    - [x] 5. How many generic fields are declared in each project?
    - [x] 6. How is varargs used over time?
    - [x] 7. How is transient keyword used in Java?
- [x] **6. Software Engineering Metrics**
    - [x] 1. What are the number of attributes (NOA), per-project and per-type?
    - [x] 2. What are the number of public methods (NPM), per-project and per-type?

**Comment by bzz** [comment]
His can be useful support for Engine adoption in academia.

Here is also a [whitepaper on Boa](http://lib.dr.iastate.edu/cgi/viewcontent.cgi?article=1373&context=cs_techreports)

**Comment by ajnavarro** [comment]
@marnovo All the questions that are related with SVN in our use case should be answered changing SVN to GIT, right?

**Comment by marnovo** [comment]
> @marnovo All the questions that are related with SVN in our use case should be answered changing SVN to GIT, right?

@ajnavarro indeed! It doesn't need to be answering the verbatim questions, of course there will be differences to be accounted for.

**Comment by bzz** [comment]
I believe those checkboxes might also be implemented in https://github.com/mcarmonaa/QuerySetApp/blob/master/src/main/scala/tech/sourced/queryset/BoaQueries.scala

**Comment by ajnavarro** [comment]
Done in: https://github.com/mcarmonaa/QuerySetApp
