### ISSUE TITLE
Find a way to publish the engine in maven without a fatjar

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#220]
Shading every dependency inside is not a very future-proof way of doing things as we need to shade everything someone from the outside might need to include.

**Comment by ajnavarro** [comment]
To be able to work with `--packages` option in Spark, I think is not possible. But we can create subprojects, one to deploy a uber-jar and another to deploy a standard one: https://stackoverflow.com/questions/19290812/publish-jar-files-with-sbt-3rd-party

**Comment by ajnavarro** [comment]
With the 0.1.11, the slim jar appears to have the same size that the fat one: http://repo1.maven.org/maven2/tech/sourced/engine/0.1.11/

**Comment by erizocosmico** [comment]
Yep, it's a fatjar. Which is weird because when I try it locally it's not a fatjar 😮

**Comment by ajnavarro** [comment]
You're right, locally is creating correctly both files... :S

**Comment by erizocosmico** [comment]
It's only because `clean` was not used.

You generate something and the default is the fatjar, the next run it does not overwrite it because nothing changed, so the task that copies the "regular" jar to the slim copies the fat jar instead.

Every time you need to generate the slim jar, it needs to be a clean build.

**Comment by erizocosmico** [comment]
Fixed in 0.1.12 http://repo1.maven.org/maven2/tech/sourced/engine/0.1.12/
