### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#232]
This issue is to add integration tests similar to the ones in [lookout](https://github.com/src-d/lookout/tree/master/cmd/server-test) or [gitbase](https://github.com/src-d/gitbase/blob/master/e2e/e2e_test.go). It should be as a go test suite.

Tasks:
- [x] Create a `make` rule that can build the binary and daemon, and run the integration tests
  - This should include the most basic test we can find, probably a `srcd init` call
  - The integration tests should not run as normal test with `go get`, we need to use a build tag or test flag.
  - Needs to be included to travis config
- [x] Add basic tests for each command
  - For now, let's ignore the output and check only the exit codes.
  - For the web interfaces we could at least do a wget and check it's not a 404.

**Comment by se7entyse7en** [comment]
The first part is #302. After that we can split the work and parallelize maybe taking one command each.

**Comment by carlosms** [comment]
One comment to consider as future improvement.
After #302 was merged I tried to run the integration tests on the released binary, skipping the build on the Makefile and downloading the bin into `build-integration/engine_linux_amd64`. The tests fail with:
```
expected: "removing container integration-testing-scrd-cli-daemon"
actual  : "removing container srcd-cli-daemon"
```

Maybe we could modify the tests to be able to run any binary, instead of the ones we build specifically for the tests. This way we can use them as kind of acceptance tests, with the released binary downloading the published docker image for srcd/cli-daemon.

**Comment by smacker** [comment]
Current state:
- [x] srcd init
- [ ] srcd stop (was used in other tests, do we need separate tests for it?)
- [ ] srcd prune
- [x] srcd version
- [ ] srcd parse (maybe the command will be removed see https://github.com/src-d/feature-idea/issues/122)
- [x] srcd sql
- [ ] srcd web parse (the command will be removed see https://github.com/src-d/feature-idea/issues/122)
- [x] srcd web sql
- [x] srcd components

**Comment by carlosms** [comment]
Thanks for the summary.
About parse being removed: until it's included in a relase planning, I think we should still treat it like any other command. Maybe let's not go crazy doing the most complex tests for it, but I think we should cover the basics at least.

**Comment by carlosms** [comment]
When we close this one for the first "wave" of tests, we'll still have some things to cover later.
Linking here so we don't forget to open issue later: [test gitbase indexes when changing workdirs](https://github.com/src-d/engine/pull/316#pullrequestreview-213503981).

**Comment by dpordomingo** [comment]
this issue is in CR kanban column, but it seems there is no more PRs to review...
