### ISSUE TITLE
[METADATA STORE] Be able to choose the tables that will be stored on the backed database

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#237]
Add a parameter to determine the amount of data that will be stored on the backed database. By default we are storing `repositories` `references` `commits` and `tree-entries`. The tables to back won't be able to choose randomly (per example, do not back `repositories` but `references`). If you choose commits per example, all the previous relations must be backed as well.

**Comment by erizocosmico** [comment]
Blocked until we implement the datasource to do this

**Comment by ajnavarro** [comment]
deprecated.
