### ISSUE TITLE
Clarify the definition of default ports, and its harcoded values

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#240]
from https://github.com/src-d/engine/pull/236#pullrequestreview-208949083

`9432`, `8081`, `8080`, `3306`, `4242` seems to be default ports for some parts of the app, so I wonder if it could be better writing them as constants on top of [`api/config.go`](https://github.com/src-d/engine/pull/236/files#diff-5b28dfc097f789fdcd262a4667e968cdR3)?

searching for that numbers in the sourcecode I found some occurrences outside of `api` package, so I wonder if that consts should be exposed publicly to be used outside instead of harcoding them where needed:
- `9432` : [`cmd/srcd-server/engine/parse.go#L22`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/parse.go#L22)
- `8080` : [`cmd/srcd-server/engine/web.go#L15`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/web.go#L15) and [`cmd/srcd-server/engine/web.go#L17`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/web.go#L17)
- `3306` : [`cmd/srcd-server/engine/sql.go#L19`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/sql.go#L19)
- `4242` : [`cmd/srcd/daemon/daemon.go#L27`](https://github.com/src-d/engine/blob/master/cmd/srcd/daemon/daemon.go#L27) and [`cmd/srcd-server/main.go#L18`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/main.go#L18)

I also found an extra harcoded port used for bblfsh ctrl protocol:
- `9433` : [`cmd/srcd-server/engine/parse.go#L23`](https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/parse.go#L23)

**Comment by smacker** [comment]
keep in mind we define public ports in api/config. They match private ones by default be can be changed. I didn't check all the code but some of it might depend on the private port instead of public one.
