### ISSUE TITLE
[METADATA STORE] Create a layer between the database and the engine to be able to marshall and unmarshall types depending of the original data type

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#242]
Sqlite supports only a few data types. To be able to save and fetch data into that database, we should add a layer to transform unsupported types into supported ones (per example, booleans into integer, arrays into strings and so on)

**Comment by ajnavarro** [comment]
Sqlite supports only a few data types. To be able to save and fetch data into that database, we should add a layer to transform unsupported types into supported ones (per example, booleans into integer, arrays into strings and so on)

**Comment by erizocosmico** [comment]
Being done in https://github.com/src-d/engine/pull/232
