### ISSUE TITLE
Add --log-format flag

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#244]
Adding the `--logfmt` could simplify the parsing of the logs during integration testing by running the cli commands with `--logfmt json` that is then propagated to [logrus formatter](https://github.com/sirupsen/logrus#formatters).

/cc @src-d/product given that the cli is user-facing.

**Comment by smacker** [comment]
I propose to change logging/cli to the standard library we use in src-d.
Then we will have `log-format` option: https://github.com/src-d/go-cli/blob/master/log.go#L11
And it will be consistent with all other projects.

**Comment by carlosms** [comment]
Yup, I brought up the idea of switching from cobra to go-cli with @smola but he thought it was not worth the extra effort to migrate.
@smola can you comment on this?

**Comment by smola** [comment]
You could start by migrating to `src-d/go-log` and adding the `--log-format` (not `--logfmt`) flag.

@carlosms  With respect to `src-d/go-cli`, last time I did this, migrating from a cobra-based CLI to a go-cli one took me a while, and it was much smaller than this one. Do you have any rough estimation of how much could this take?

**Comment by carlosms** [comment]
@smola I did a quick and dirty test, migrating `srcd init`

I don't want to be super optimistic, but the migration was not painful at all. There might be a few things that won't match. For example, go-cli already has a version command, we have our own in Engine.

I'd say this is not  a huge task. A few _working_ hours, meaning a few _real_ days depending on what other tasks we have to deal with.

See
- https://github.com/carlosms/engine/tree/go-cli/cmd
- https://github.com/src-d/engine/compare/master...carlosms:go-cli

**Comment by smola** [comment]
@carlosms Let's go for it then ;)

**Comment by carlosms** [comment]
Done in #410.
