### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by smacker** [src-d/engine#251]
1. Not sure about powershell but `cmd.exe` expects `"` instead of `'` for paths with space. Copy-past of current command from readme fails.
2. `mv` on windows called `move`

**Comment by se7entyse7en** [comment]
WRT the documentation, should we also add that Windows support is currently experimental?

**Comment by carlosms** [comment]
I would put that in the release notes.

**Comment by carlosms** [comment]
Let's also clarify in the docs if the commands are cmd.exe or powershell. I think @se7entyse7en you mentioned that all tests were done in powershell, so it looks like a safer option.
