### ISSUE TITLE
Warning about version

### ISSUE THREAD

**Issue by smacker** [src-d/engine#252]
This `WARN` is returned always.
What does it mean? 
What can I do as a user?

```shell
$ srcd init /projects/src/github.com/torvalds
WARN[0001] unable to list the available daemon versions on Docker Hub: 
can't find compatible image in docker registry for srcd/cli-daemon 
```

![image](https://user-images.githubusercontent.com/406916/53729949-e032cf00-3e76-11e9-8c5a-5dba0c075b00.png)

**Comment by carlosms** [comment]
This probably happens because the release is `-rc`

**Comment by smacker** [comment]
Yep. Maybe we should add support for `-rc` versions.
