### ISSUE TITLE
srcd web sql hangs if docker was restarted

### ISSUE THREAD

**Issue by smacker** [src-d/engine#253]
Run `srcd web sql` without any images and restart docker while its downloading/installing dependencies to reproduce

**Comment by carlosms** [comment]
What do you mean by "hangs"? Do you think we should detect the docker service restart, and exit the command? Or restart the containers?

**Comment by smacker** [comment]
> What do you mean by "hangs"

<img width="689" alt="Screenshot 2019-04-04 at 14 28 39" src="https://user-images.githubusercontent.com/406916/55555613-f5a15000-56e5-11e9-9a10-2f826c5314da.png">

> Do you think we should detect the docker service restart, and exit the command? Or restart the containers?

I think it should do something not important what exactly because it's not "normal" case. Just showing error like "connection to docker was lost" or something like that would be enough.

**Comment by se7entyse7en** [comment]
I wasn't able to reproduce this locally. I got both
```
could not start gitbase: rpc error: code = Unavailable desc = transport is closing
```
and
```
could not start gitbase web client: rpc error: code = Unavailable desc = transport is closing
```
@smacker did it happened to you also on OSX or on Windows only? Or maybe this has been fixed as a side-effect of some other issues that we solved.

**Comment by smacker** [comment]
I stumbled on this bug on windows and didn't test it on mac.
This might be fixed by a new "ping" feature.
But just to be sure, did you test it with or without images?

**Comment by se7entyse7en** [comment]
I ran a `srcd prune --with-images` before testing it.

**Comment by smacker** [comment]
ok. thanks! let's close it then.
