### ISSUE TITLE
getHEAD method is filtering by refs/heads/HEAD instead of HEAD in bare or standard repositories formats.

### ISSUE THREAD

**Issue by bzz** [src-d/engine#255]
This might or might not be connected to #254 but on similar use case of using Engine on a local Git repository and trying to count number of commits, one gets unexpected result.

Steps to reproduces:
```
mkdir test-repo-root
cd test-repo-root; git clone git@github.com:bblfsh/client-scala.git; cd -

"${SPARK_HOME}"/bin/spark-shell --packages "tech.sourced:engine:0.1.12"
```

And then

```
import tech.sourced.engine._
val engine = Engine(spark, "./test-repo-root/")
engine.getRepositories.getHEAD.getCommits.getFirstReferenceCommit.count
```
results in `0`.

Expected results would be closer to
```
$ cd
$ git rev-list HEAD --count
125
```

**Comment by erizocosmico** [comment]
Checking this.

It's weird because there are commits, like, for sure: 

```
scala> engine.getRepositories.filter("id like 'file%'").getReferences.getCommits.count()
res6: Long = 1783
```

But for some reason with `getFirstReferenceCommit` they disappear. Will take a closer look.

**Comment by bzz** [comment]
Thank you @erizocosmico ! Workaround works good, and we can switch back to getHead after new 0.2.x version with a fix is released

**Comment by erizocosmico** [comment]
One thing this does not take into account are remote heads, which are something like `refs/remotes/{REMOTE_NAME}/HEAD`. I imagine the solution you need has to take these into account as well, amirite?
