### ISSUE TITLE
srcd sql prints weird characters on windows

### ISSUE THREAD

**Issue by smacker** [src-d/engine#257]
https://user-images.githubusercontent.com/406916/53730491-63a0f000-3e78-11e9-955c-b8b7ce74c480.png

**Comment by carlosms** [comment]
related: #154

**Comment by smacker** [comment]
this particular bug is solved but there are still weird characters in some cases. Let's fix them in this issue. Details: https://github.com/src-d/engine/issues/379#issuecomment-477958725
