### ISSUE TITLE
Port conflict error is not very user friendly

### ISSUE THREAD

**Issue by smacker** [src-d/engine#258]
It's also hard to find information how to fix conflict (using config file)

```shell
$ srcd sql "SHOW tables;"
FATA[0000] could not start gitbase: rpc error: code = Unknown desc = could not create srcd-cli-bblfshd:
could not start container: srcd-cli-bblfshd: Error response from daemon:
driver failed programming external connectivity on endpoint srcd-cli-bblfshd (8545...):
Bind for 0.0.0.0:9432 failed: port is already allocated 
```

Screenshot from the empathy session log:
![image](https://user-images.githubusercontent.com/406916/53733741-36f1d600-3e82-11e9-8cd4-40e555ad3cce.png)

**Comment by carlosms** [comment]
Screenshot from the empathy session log:
https://user-images.githubusercontent.com/406916/53733741-36f1d600-3e82-11e9-8cd4-40e555ad3cce.png

**Comment by dpordomingo** [comment]
I also found this issue

I'd expect:

```shell
$ srcd sql "SHOW tables;"
FATAL[0000] could not start gitbase. Port 9432 is already allocated.
You can define the port to be binded by ${service} in ${confFile} under ${portName}, and then run:
'srcd init ${workdir} --config ${confFile}'
```
where:
- `${workdir}` is `/path/to/workdir`
- `${confFile}` is `~/.srcd/config.yml`
- `${service}` is `srcd-cli-bblfshd`
- `${portName}` is `components.bblfshd.port`
