### ISSUE TITLE
Create a set of queries that allow us to test engine performance between versions.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#260]
Research a set of queries that test different parts of the engine, to be able to measure times between versions to check if we are actually improving engine or not.

**Comment by EgorBu** [comment]
If it may help: 
`Spark Performance Tests` from Databricks https://github.com/databricks/spark-perf

**Comment by EgorBu** [comment]
and we can prepare list of queries that we are using in https://github.com/src-d/apollo.
Can it be useful for you?

**Comment by mcarmonaa** [comment]
Yes, it would be very helpful. Thanks @EgorBu !

**Comment by EgorBu** [comment]
I tried to remove external dependencies as much as possible (but still in one place it depends on `src-d/ml`).
Here it is:

<details>

```python
# Extract commits
commits = engine.repositories.references.head_ref.commits
commits = engine.repositories.references.head_ref.commits.filter(commits.index <= some_number)

# Extract files
files = commits.tree_entries.blobs

#-----------------------------------------------
# Extract UASTs
files = files.dropDuplicates(("blob_id",)).filter("is_binary = 'false'")
classified = files.classify_languages()
languages = ["Java", "Python"]
lang_filter = classified.lang == languages[0]
for lang in languages[1:]:
    lang_filter |= classified.lang == lang
filtered_by_lang = classified.filter(lang_filter)
uasts = filtered_by_lang.extract_uasts()

#-----------------------------------------------
# Persistence
# Usually some_persistence_level is MEMORY_ONLY
uasts = uasts.persist(some_persistence_level)

#-----------------------------------------------
# Dump to cassandra
def format_url(row):
    if row.repository_id.startswith("github.com"):
        return "https://%s/blob/%s/%s" % (row.repository_id, row.commit_hash, row.path)
    if row.repository_id.startswith("bitbucket.org"):
        return "https://%s/src/%s/%s" % (row.repository_id, row.commit_hash, row.path)
    return "[%s %s %s]" % (row.repository_id, row.commit_hash, row.path)

rows = uasts.rdd.map(lambda x: Row(sha1=x.blob_id, url=self.format_url(x)))

table = "test_table"
keyspace = "test_keyspace"
rows.toDF().write.format("org.apache.spark.sql.cassandra").mode("append").options(table=table, keyspace=keyspace).save()

#-----------------------------------------------
# Deserialize UAST
from bblfsh.sdkversion import VERSION
parse_uast = importlib.import_module(
    "bblfsh.gopkg.in.bblfsh.sdk.%s.uast.generated_pb2" % VERSION
).Node.FromString

def deserialize_uast(row):
    if not row.uast:
        return
    row_dict = row.asDict()
    row_dict["uast"] = parse_uast(row.uast[0])
    yield Row(**row_dict)

uasts = uasts.rdd.flatMap(deserialize_uast)

#-----------------------------------------------
# Extract Document Frequencies
from sourced.ml.repo2 import wmhash
extractors = [wmhash.__extractors__[extr]() for extr in wmhash.__extractors__]

def process_row(self, row):
    yield self.NDOCS_KEY, 1
    for i, extractor in enumerate(self.extractors):
        for k in extractor.inspect(row.uast):
            yield (i, k), 1

processed = uasts.flatMap(self.process_row)
reduced = processed.countByKey()
# Do something with frequencies
print(len(reduced.items())

#-----------------------------------------------
# Repo2WeightedSet
def process_row(self, row):
    bag = {}
    for extractor in extractors:
        bag.update(extractor.extract(row.uast))
    return row.blob_id, bag

bags = uasts.map(process_row)

#-----------------------------------------------
# Persistent bags
bags = bags.persist(some_persistence_level)
```
</details>

**Comment by mcarmonaa** [comment]
#218 is related to this task since we can use some to the queries from there.

**Comment by mcarmonaa** [comment]
Since there's no a repository created for this task, I've created a repository [QuerySetApp](https://github.com/mcarmonaa/QuerySetApp) in my personal account.

I'm using queries from #218, so both issues are being addressed at the same time because the cases exposed there are good examples of usage. Thus, they should be valid samples to test performance too.

The issue #277 must be fixed to complete this, so it's a work in progress right now.

I realized that some queries (like those related to licenses) show some lacks in the engine api. I write some code in the [QuerySetApp](https://github.com/mcarmonaa/QuerySetApp) to append license types to blobs that could be valuable to add a list or licenses per project in the Repository DataFrame.

Another data it would be great to have in the Repository DataFrame are the languages used in each project, ordered by usage.

[...]

**Comment by bzz** [comment]
Just FYI, but `number of uniq hashes` was something that people in academia are already interested in because that will allow head-to-head comparison with Software Heritage dataset.

**Comment by mcarmonaa** [comment]
@bzz when you say `number of uniq hashes` you mean for all git objects or per git objects(commits, trees, blobs, tags)?

**Comment by bzz** [comment]
I believe at this scale, it's only a total number of all git objects.

Another very simple, but useful query that all of the applications use so far and no doubt you already know about is - iterating all the files at latest commit of the main branch of non-forks.

**Comment by eiso** [comment]
I want to tag @campoy here since these queries and use cases are highly relevant tutorials/examples for documentation

**Comment by mcarmonaa** [comment]
Done in this [repo](https://github.com/mcarmonaa/QuerySetApp)

**Comment by spier** [comment]
@dpordomingo My bad, I did not realise that the last comment was for me.

I have used the `--signoff` feature now and have pushed my changes again.

Please review. Thanks.
