### ISSUE TITLE
web parse: Incomplete role for very common structure

### ISSUE THREAD

**Issue by smacker** [src-d/engine#261]
`go:SelectorExpr` has role `Incomplete` which is weird.

**Comment by carlosms** [comment]
Where should we transfer this issue? go-driver? bblfshd?

**Comment by carlosms** [comment]
cc @src-d/language-analysis

**Comment by dennwc** [comment]
Go driver

**Comment by carlosms** [comment]
There is no issue transfer between organizations. Can you please @smacker open an issue in bblfsh/go-driver?

**Comment by smacker** [comment]
https://github.com/bblfsh/go-driver/issues/42
