### ISSUE TITLE
srcd parse uast never finishes

### ISSUE THREAD

**Issue by smacker** [src-d/engine#270]
```
$ ./srcd parse uast aws-sdk-php/src/data/ec2/2016-11-15/docs-2.json.php
INFO[0000] detected language: php
INFO[0003] if this is the first time using a driver for a language, this might take a few more minutes while we install it
```
and it just hangs

(you might need to re-run this command multiple times to get the hanging)

**Comment by dpordomingo** [comment]
might be related to https://github.com/src-d/engine/issues/296

did you check the container logs?
```shell
$ docker logs -f srcd-cli-bblfshd
```

**Comment by smacker** [comment]
Not related. More information about this bug in the log: https://github.com/src-d/empathy-sessions/issues/35

**Comment by se7entyse7en** [comment]
@smacker I tried with the same file, but I wasn't able to reproduce this. I first ran `srcd prune` and then `srcd parse uast` multiple times. Are you able to reproduce this sistematically?

**Comment by smacker** [comment]
I can't reproduce now. Most probably it was side-effect of the bug with not-working sql query cancel.
According to the logs I run the query first (most probably even more than 1).
If it was still running in background it could consume all available driver instances. 

I can "kind of" reproduce it when I run 5 queries in the background. But it's expected. Closing.
