### ISSUE TITLE
performance and resources releasing

### ISSUE THREAD

**Issue by mcarmonaa** [src-d/engine#279]
Related to the empathy session.

running this query locally either on `srcd sql` or on `srcd web sql` makes my laptop got frozen
```sql
SELECT * FROM (
    SELECT cf.file_path,
           UAST(f.blob_content, LANGUAGE(f.file_path,  f.blob_content)) as uast
    FROM ref_commits r
    NATURAL JOIN commit_files cf
    NATURAL JOIN files f
    WHERE r.ref_name = 'HEAD'
    AND r.history_index = 0
) t WHERE uast != '';
```

This is the list of repositories I was using:
- github.com/srcd-/gitbase
- github.com/srcd-/gitbase-web
- github.com/bblfsh/bblfshd
- github.com/apache/spark
- github.com/spring-projects/spring-boot
- github.com/spring-projecst/spring-framework

Is this the expected behavior?

Also running a lighter query that was taking too long
```sql
SELECT repository_id, blob_content
FROM files
WHERE file_path = 'LICENSE'
OR file_path = 'README.md';
```
I noticed that after cancel the query the resources aren't release (at least properly, maybe the different services involved continue running the query) so I had to call `srcd stop`

**Comment by carlosms** [comment]
Should we consider adding resource constraints to the gitbase container?

About 

> I noticed that after cancel the query the resources aren't release (at least properly, maybe the different services involved continue running the query) so I had to call srcd stop
It looks like this is the same problem as https://github.com/src-d/engine/issues/281, should be fixed by https://github.com/src-d/engine/issues/282
