### ISSUE TITLE
start-notebook.sh is not present in image anymore

### ISSUE THREAD

**Issue by smeruelo** [src-d/engine#280]
## Expected Behavior
https://github.com/src-d/infrastructure/tree/master/engine-jupyter-demo expects `start-notebook.sh` to exist because it runs the container [this way](https://github.com/src-d/infrastructure/blob/8f59a2e6370bd57bd60f0fb73a0fdef8cd92e3d9/engine-jupyter-demo/startup.sh#L120)

## Current Behavior
Dec 22 11:10:46 demo-01 systemd[1]: Started Spark API Jupyter Notebook Service.
Dec 22 11:10:46 demo-01 docker[24713]: container_linux.go:265: starting container process caused "exec: \"start-notebook.sh\": executable file not found in $PATH"
Dec 22 11:10:47 demo-01 docker[24713]: /usr/bin/docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"start-notebook.sh\": executab
Dec 22 11:10:47 demo-01 systemd[1]: engine-jupyter.service: Main process exited, code=exited, status=127/n/a
Dec 22 11:10:47 demo-01 docker[24902]: Error response from daemon: No such container: engine-jupyter

## Possible Solution
Maybe some path variable or symbolic link is missing? Or just provide us with the new procedure we should be using to launch the container

## Steps to Reproduce (for bugs)
1. git clone https://github.com/src-d/infrastructure.git
2. cd infrastructure/engine-jupyter-demo
3. ./create-demo-node.py --node-id=2 --engine-jupyter-version=v0.3.1

**Comment by jfontan** [comment]
The base image that contained jupyter, spark and other dependencies to one done ad-hoc for engine. This new image does not have a script that starts jupyter notebook. It's done calling jupyter directly:

```
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root"]
```

This change should fix service start:

```
ExecStart=/usr/bin/docker run --name engine-jupyter --rm -p 80:8888 -p 4040:4040 --env SPARK_LOCAL_DIRS=${SPARK_TMP} --env SPARK_DRIVER_MEMORY=${SPARK_DRIVER_MEMORY} --tmpfs ${SPARK_TMP} -v /user-workdir:${USER_WORKDIR} -v ${REPOSITORIES}:${REPOSITORIES} --link bblfshd:bblfshd srcd/engine-jupyter:${ENGINE_JUPYTER_VERSION} jupyter notebook --ip=0.0.0.0 --allow-root --NotebookApp.password=${NOTEBOOK_PASSWORD}
```

**Comment by smeruelo** [comment]
Many thanks, @jfontan. I've been able to successfully create one now.
