### ISSUE TITLE
Ensure that ports can be used when initializing Engine

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#289]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470034422
related to https://github.com/src-d/engine/issues/273

It can be ran `srcd init` with already used ports, and it won't complain:

```shell
srcd init /projects/src/github.com/torvalds --config conf/conf.default.yml 
INFO[0000] starting daemon with working directory: /projects/src/github.com/torvalds 
```

...until they're required for each component, that will cause Engine to fail

```shell
$ srcd sql "SHOW tables;"
FATA[0000] could not start gitbase: rpc error: code = Unknown desc = could not create srcd-cli-bblfshd:
could not start container: srcd-cli-bblfshd: Error response from daemon:
driver failed programming external connectivity on endpoint srcd-cli-bblfshd (8545...):
Bind for 0.0.0.0:9432 failed: port is already allocated 
```

I wonder if ports from config could be checked once Engine starts.

**Comment by carlosms** [comment]
I don't know if we should start checking everything for the future success of other commands. I mean, you could check the port on `init`, then the user starts a server that takes the port, and later the `sql` will fail... Or we could also check if there are any docker containers using the name of our containers...

But I agree with the feeling that `init` should leave things ready to use. Maybe we should at least start gitbase and bblfsh on `init`?

**Comment by dpordomingo** [comment]
Considering the big picture: where Engine could work with more components, or even being injected on demand, it makes no sense forcing `init` to check (or reserve) all ports given by config.

The current solution also forces the user to restart everything, what could be a bad UX if there are things already running over already started services.

What would work?
If the user would be able to change the config without removing and restoring everything.

example:
```shell
$ srcd init --config conf.default.yml
$ srcd parse uast /huge/file # taking a long time
$ srcd sql "SELECT *"
FATAL[0000] could not start gitbase. Port 3306 is already allocated.
            You can define a port for srcd-cli-engine running:
            'srcd conf set components.bblfshd.port <port>'
$ srcd conf set components.bblfshd.port 3307
$ srcd sql "SELECT *"
+-------+
| DUMMY |
+-------+
| x     |
+-------+

**Comment by dpordomingo** [comment]
no going to happen
