### ISSUE TITLE
Make getFirstReferenceCommit the default behavior

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#290]
## Expected Behavior

Instead of retrieving all commits of all references of all repositories, only the first reference commit (aka the current state of the reference) should be retrieved by default.
Instead of a `getFirstReferenceCommit` we can add a `getAllReferenceCommits` for the old behavior.

## Current Behavior

Retrieves all commits from all references from all repos by default.

## Possible Solution

Make `getFirstReferenceCommit` default, add a `getAllReferenceCommits` to opt-in into old default behavior.

## Steps to Reproduce (for bugs)

n/a

## Context

The rationale behind this is that most of the time what you want is `getFirstReferenceCommit`, which is the obvious thing a person would expect engine to do. If you want the more detailed output provided by `getAllReferenceCommits` you are opting in into this, which you already know will severely harm the performance of the job you're running.

So, this as a default that makes more sense for the following reasons:

- More obvious behavior for newcomers
- Default that does not severely impact performance
- Previous effect can still be achieved

## Your Environment

n/a

Also, /cc @vmarkovtsev @bzz as users what do you think about this?

**Comment by vmarkovtsev** [comment]
I am strongly +1

**Comment by eiso** [comment]
+1

**Comment by ajnavarro** [comment]
LGTM

**Comment by bzz** [comment]
That sounds as a great default indeed, thank you @erizocosmico !

**Comment by erizocosmico** [comment]
Will write an ENIP for it, then.
