### ISSUE TITLE
Port error message doesn't tell the truth 

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#290]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470036325

The error message logged when there is a port conflict says that the container could not be created, and it is not listed in `srcd components list`

```shell
$ srcd sql "SHOW tables;"
FATA[0000] could not start gitbase: rpc error: code = Unknown
desc = could not create srcd-cli-bblfshd:
could not start container: srcd-cli-bblfshd: Error response from daemon:
driver failed programming external connectivity on endpoint srcd-cli-bblfshd (8545...):
Bind for 0.0.0.0:9432 failed: port is already allocated 

$ srcd components list
IMAGE                             INSTALLED    RUNNING    CONTAINER NAME
bblfsh/bblfshd:v2.11.8-drivers    yes          no         srcd-cli-bblfshd
```

but it was created ~and is running~ if listed with docker

```shell
$ docker ps -a
CONTAINER  IMAGE                        COMMAND              CREATED  STATUS   PORTS  NAMES
fc2f408    bblfsh/bblfshd:v2.11-drivers "bblfshd -ctl-add…"  1s ago   Created         srcd-cli-bblfshd
```

**Comment by se7entyse7en** [comment]
> $ docker ps -a
CONTAINER  IMAGE                        COMMAND              CREATED  STATUS   PORTS  NAMES
fc2f408    bblfsh/bblfshd:v2.11-drivers "bblfshd -ctl-add…"  1s ago   Created         srcd-cli-bblfshd

Was this the full output of `docker ps -a`?

Because actually, it seems that the behavior is correct. The log says that it cannot *start* the container and `docker ps -a` shows the status as *`Created`* and not as `Up X`. But if the port was actually free, the problem is different and we should understand why the container hasn't been started.

**Comment by smacker** [comment]
Tried to reproduce:
```
$ ./srcd stop
$ docker run -it --rm --privileged -p 9432:9432 -d bblfsh/bblfshd:v2.11.8-drivers
96924ed90f9e96194c849a8b6dd87548411fac1f8cd2aa9f728b01c539536821

$ ./srcd sql "SHOW tables;"
FATA[0003] could not start gitbase: rpc error: code = Unknown desc = could not create srcd-cli-bblfshd: could not start container: srcd-cli-bblfshd: Error response from daemon: driver failed programming external connectivity on endpoint srcd-cli-bblfshd (47032a615be721e3162ec60f30a01144a809280e7d069fdb08551c51a23d5846): Bind for 0.0.0.0:9432 failed: port is already allocated

$ docker ps
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                    NAMES
39b043496b23        srcd/cli-daemon:latest           "/srcd-server --work…"   24 seconds ago      Up 23 seconds       0.0.0.0:4242->4242/tcp   srcd-cli-daemon
96924ed90f9e        bblfsh/bblfshd:v2.11.8-drivers   "bblfshd"                35 seconds ago      Up 34 seconds       0.0.0.0:9432->9432/tcp   angry_merkle
```

looks correct.

@dpordomingo do you remember maybe you did something else?
It looks weird that you got `port is already allocated error` but `srcd-cli-bblfshd` was created.
It's not really possible with docker... (at least as far as I know)

**Comment by dpordomingo** [comment]
I wrote "_... (the container) was created and is running if listed with docker_", but "_is running_" is not true as it could be seen in my own issue description :woman_facepalming: (as @se7entyse7en said, it was only "created", but not yet started).
Anyhow, I think that if Engine detected a problem, it could also remove the created container.

But it could be also considered an expected behavior: create, try to start, and leave it created but down if a problem was found during its initialization.
If it's that way, feel free to close this issue :dagger:

**Comment by se7entyse7en** [comment]
> Anyhow, I think that if Engine detected a problem, it could also remove the created container.

I actually like this idea, as a sort of teardown in case of failure. In this case, the error was actually straightforward (busy port), but I'm wondering whether the teardown is actually not wanted by the user. For example, if the user wants to run an interactive shell inside the container to debug what didn't work.

**Comment by dpordomingo** [comment]
I tried to access the created container, but since it is not running you can not run a shell inside ;)

**Comment by se7entyse7en** [comment]
Isn't it possible to start the created container with a different entrypoint?

**Comment by dpordomingo** [comment]
I tried `docker start` over that created container, and it cried about an already used port.
And it seems it does not let you change entrypoint nor ports...

The alternative could be:
```shell
$ docker commit srcd-cli-gitbase local_srcd-cli-gitbase
$ docker run -it --entrypoint=/bin/sh local_srcd-cli-gitbase
```

But I'm not sure if it should be the way to proceed when source{d} Engine could not create a component.

**Comment by se7entyse7en** [comment]
If it is not possible to change the entrypoint than I don't think that it makes much sense.

**Comment by smacker** [comment]
you can get logs from a stopped container. So I would better keep the current behavior. It helps with debugging. Cleaning up happens anyway every time you `init/stop/prune` or restart the component.

**Comment by smacker** [comment]
Do we have any conclusion on it?

**Comment by smacker** [comment]
we agreed it's a feature and we don't want to change the behaviour at least for now
