### ISSUE TITLE
Add a success message in the `init` command

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#292]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470038291

When the last message is a `WARN` saying that something could not be done, the user can thing that the `init` process did not succeed.

```shell
$ srcd init /projects/src/github.com/torvalds
INFO[0000] removing container srcd-cli-daemon           
INFO[0000] starting daemon with working directory: /projects/src/github.com/dpordomingo/empathy-sessions/4-engine 
WARN[0001] unable to list the available daemon versions on Docker Hub: can't find compatible image in docker registry for srcd/cli-daemon 
```

I'd purpose to add a succeeds message?

**Comment by carlosms** [comment]
related: #252

**Comment by carlosms** [comment]
We should take a look at the current actions and try to be consistent, because I think for some of them we do log a "done" message.

**Comment by dpordomingo** [comment]
consistency matters! :up:

**Comment by se7entyse7en** [comment]
With #302 that was merged after you did the empathy session, we introduced a `daemon started` info message once the init completed successfully. I think that we can close this.
