### ISSUE TITLE
Let the user to start components

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#298]
discovered at https://github.com/src-d/empathy-sessions/issues/37#issuecomment-470046657
causes https://github.com/src-d/engine/issues/299

In order to use source{d} Engine components with external clients as described by [Clients and Connectors](https://docs.sourced.tech/engine#clients-and-connectors) 
>_to connect to the language parsing server (Babelfish) and analyzing the UAST, there are several language clients_

it is required to run those components with `srcd components start`, but [that command does not exist](https://github.com/src-d/engine/blob/master/docs/commands.md#srcd-components-start).

**Comment by carlosms** [comment]
Related to #321

**Comment by carlosms** [comment]
Done in #433.
