### ISSUE TITLE
Or filters are not correctly compiled

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#303]
## Expected Behavior

Or filters should be compiled into or filters

## Current Behavior

Or filters are compiled into And filters in `matchingCases` because they extend from `BinaryFilter` and what it does is `left.matchingCases ++ right.matchingCases`

## Possible Solution

Support only and filters for the time being until a refactor of the filters is properly done. It's not like it's not gonna work, Spark will take care of it. It's just that it'd be more efficient if we did it.

https://github.com/src-d/engine/blob/master/src/main/scala/tech/sourced/engine/util/Filters.scala#L80 and `s/BinaryFilter/AndFilter/` in that line would do the trick.

## Steps to Reproduce (for bugs)

Create any or filter

## Context

I came up with this while currently working on the implementation of the ENIP 004. It's proven to be trickier than I initially thought. So far, with the current limitations our filter system has I see it very unlikely that we're going to be able to provide an `or` filter solution for the time being.

## Your Environment (for bugs)

happens in all envs

**Comment by ajnavarro** [comment]
Can be the correct vehavior? If we process all the ORs subfilters as ANDs, the obtained subset of data sent to Spark side can be smaller than the hole dataset, and then, Spark will apply correctly OR filters.

**Comment by erizocosmico** [comment]
Yes, it's actually the correct solution as we discussed in the meeting. I'm keeping it in the refactor of the filters.

**Comment by erizocosmico** [comment]
@ajnavarro it's actually not correct. AND is not a subset of OR, AND is a subset of OR.

A and B requires A and B to be true, OR only one of them. So `a = 4 OR a = 5` is `a = 4 AND a = 5` which is always false. Thus, OR filters cannot be converted to ANDs.

**Comment by ajnavarro** [comment]
@erizocosmico right.
