### ISSUE TITLE
Dockerfile base image is not public (or doesn't exist)

### ISSUE THREAD

**Issue by campoy** [src-d/engine#304]
## Expected Behavior

Building the `Dockerfile` at the root of this repository should work.

## Current Behavior

```bash
$ docker build .
Sending build context to Docker daemon  2.167MB
Step 1/16 : FROM srcd/jupyter-spark:5.2.1
pull access denied for srcd/jupyter-spark, repository does not exist or may require 'docker login'
```

## Possible Solution
`srcd/jupyter-spark` should be public

**Comment by rporres** [comment]
Taking a look

**Comment by rporres** [comment]
Image does not exist... https://hub.docker.com/r/srcd/jupyter-spark/

@jfontan - you worked on this. Can you take a look? Let me know if you need any help pushing to DockerHub

**Comment by jfontan** [comment]
The image was there 8 days ago but it seems it was deleted. I've just uploaded it again.

**Comment by campoy** [comment]
Do we have any tool building those Dockerfiles regularly?
It'd be nice to see that they work

**Comment by erizocosmico** [comment]
@jfontan is the `Dockerfile` for that image somewhere? Perhaps we should put it in a repo with it's own CI stuff to autopublish the images on each build

**Comment by jfontan** [comment]
The dockerfile for the base image is in this repo:

https://github.com/src-d/jupyter-spark-docker

The build + upload was not automated because we didn't foresee it to change for the time being. Even if this was automated (new image when the repo changes) it would not fix the problem we had. The image was deleted from the docker hub.

**Comment by mcuadros** [comment]
The build of the Dockerfile should be handle with https://github.com/src-d/ci, on Travis based on semver releases. 

How was removed? This is very stange.

**Comment by jfontan** [comment]
AFAIK there are no logs from docker hub so I can not know how it was deleted.

**Comment by jfontan** [comment]
The changes are already at https://github.com/jfontan/jupyter-spark-docker/tree/travis. Waiting for https://github.com/src-d/ci/pull/53 to be merged.

**Comment by erizocosmico** [comment]
Shall we close this issue, then?

**Comment by jfontan** [comment]
I've created this issue in the docker image repo to keep track of it:

https://github.com/src-d/jupyter-spark-docker/issues/3

I believe we can close this issue.
