### ISSUE TITLE
Sometimes engine/spark don't cleanup tmp directories after finish

### ISSUE THREAD

**Issue by smacker** [src-d/engine#309]
## Expected Behavior
All temporary files are removed after the job is done

## Current Behavior
The statement above isn't always true.
Currently on one of the containers:
```
root@p-spark-worker-qjcz8:/# ls /spark-temp-data/spark-* | wc -l
921
```

I will try to investigate more. When it happens and how to reproduce it. The issue is more for myself to don't forget about it.

**Comment by erizocosmico** [comment]
Not the ideal solution but maybe helpful: https://stackoverflow.com/a/30196081

**Comment by erizocosmico** [comment]
@ajnavarro shall we close this issue? Nothing we can do on our side.

**Comment by ajnavarro** [comment]
Closing the issue because is a Spark behavior that we cannot change. Feel free to open it again if you have any questions.
