### ISSUE TITLE
[API] Prepare "repository index" and incorporate it in API

### ISSUE THREAD

**Issue by bzz** [src-d/engine#32]
Right now, in order to get URLs or the repositories, or languages we need to traverse all .siva files and extract original repo urls from config.

This issue is about speeding it up by pre-computing a dataset of `original repo url`, `init_ hash`, `languages`

It has 2 parts:
 - prepare a dataset, using Spark API
 - incorporate it into the Spark API so it is used for filtering, instead of traversing .siva files

**Comment by ajnavarro** [comment]
Related to https://github.com/src-d/engine/issues/166 and https://github.com/src-d/backlog/issues/795

**Comment by ajnavarro** [comment]
Superseded by https://github.com/src-d/engine/issues/242
