### ISSUE TITLE
gitbase v0.19 fails to start due to index issues

### ISSUE THREAD

**Issue by campoy** [src-d/engine#325]
I updated the engine to v0.11 and it stopped working.

After some investigation and cleaning up the docker environment I can still reproduce:

```
12:16 ~ ➜  docker system prune -af
Total reclaimed space: 0B
12:16 ~ ➜  docker ps
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
12:16 ~ ➜  srcd version
srcd cli version: v0.11.0
docker version: 1.39
srcd daemon version: not running
12:16 ~ ➜  srcd init src/github.com/campoy
INFO[0000] starting daemon with working directory: /Users/francesc/src/github.com/campoy
INFO[0000] installing "srcd/cli-daemon:v0.11.0"
INFO[0004] installed "srcd/cli-daemon:v0.11.0"
INFO[0006] creating srcd-cli-network docker network
12:16 ~ ➜  srcd sql "select  * from repositories;"
INFO[0003] this is taking a while, if this is the first time you launch sql client, it might take a few more minutes while we install all the required images
INFO[0089] installed \"bblfsh/bblfshd:v2.11.8-drivers\"
INFO[0089] starting bblfshd daemon
INFO[0091] installing \"srcd/gitbase:v0.19.0\"
INFO[0095] installed \"srcd/gitbase:v0.19.0\"
INFO[0192] waiting for gitbase to be ready ⠹
```

When I look at the gitbase container logs, I see the cause:

```
...
time="2019-03-13T19:19:36Z" level=debug msg="repository added" path=/opt/repos/whispering-gophers.bak
time="2019-03-13T19:19:36Z" level=debug msg="registered database to catalog" db=gitbase
time="2019-03-13T19:19:36Z" level=debug msg="registered all available functions in catalog"
time="2019-03-13T19:19:36Z" level=debug msg="created index storage"
time="2019-03-13T19:19:36Z" level=debug msg="registered pilosa index driver"
time="2019-03-13T19:19:36Z" level=info msg="squash tables rule is enabled"
time="2019-03-13T19:19:36Z" level=fatal msg="unable to initialize database engine" error="index read failed: EOF"
```

I'm not sure whether this is a new or old issue, but I had not noticed until trying out Engine v0.11.

**Comment by carlosms** [comment]
Did you try to delete your `~/.srcd/gitbase/` folder?

I wonder if this can be caused by index data from an older gitbase version. I assume you have used gitbase over `/Users/francesc/src/github.com/campoy` before? What was your previous version?

**Comment by campoy** [comment]
I moved `~/.srcd` to `~/.srcd.bak` and the error subsists.

I can provide the current folder contents and the previous ones if that helps.

I'm not sure of what version I was using before, unfortunately.

**Comment by campoy** [comment]
I just tried with a different folder it works ... so it's related to something inside of my `github.com/campoy`.
I investigated a bit and it seems there was a `.siva` file that might have been corrupt.

Interestingly enough, when I try to recreate the issue the error message is now different and tells me which repository wasn't loadable.

I'll close this as non-reproducible.
