### ISSUE TITLE
run engine on pyspark with python3

### ISSUE THREAD

**Issue by zurk** [src-d/engine#330]
I want to use sourced-engine with sourced-ml, so I should make it work on python3, since sourced-ml work only with Python 3. I use awesome [guide](https://github.com/src-d/company/blob/master/documentation/ml/engine_staging.md) from @vmarkovtsev which explains how to run everything on our stage server. It works well if I need to run python2. But if I do all the same with python3 and run this code in pyspark: 
```python
from sourced.engine import Engine
engine = Engine(spark, "hdfs://hdfs-namenode:8020/apps/borges/1k", "siva")
engine.repositories.select("id").count()
```
I get this error message.
```
java.io.InvalidClassException: org.apache.spark.sql.SparkSession; local class incompatible: stream classdesc serialVersionUID = -9221993187461775747, local class serialVersionUID = -8252884317997125754
```
The full message is here [err.log](https://github.com/src-d/engine/files/1716568/err.log).

## Expected Behavior
Return the result, which I get with python2: `954`

## Current Behavior
Get an exception (see above).

## Steps to Reproduce (for bugs)
To make everything fork with python3 I do
```bash
apt update
apt install python3 python3-dev
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
pip3 install pyspark==2.2.0.post0 sourced-engine
python3 -m zipfile -c sourced-engine.zip /usr/local/lib/python3.4/dist-packages/sourced/
export PYSPARK_PYTHON=python3
export PYSPARK_PYTHON_DRIVER=python3
pyspark --py-files sourced-engine.zip -c 'spark.local.dir=/spark-temp-data' --total-executor-cores 32 --driver-memory 16g --executor-memory 4g --master "spark://p-spark-master:7077" --packages "tech.sourced:engine:0.5.1"
```
it gives me a python3 console where I run the same code 
```python
from sourced.engine import Engine
engine = Engine(spark, "hdfs://hdfs-namenode:8020/apps/borges/1k", "siva")
engine.repositories.select("id").count()
```
and last command gives me an error.

Any ideas?

**Comment by vmarkovtsev** [comment]
This error means that the version of PySpark does not match the version of the running Spark server. Can be because of Python 2 (server) - 3 (client) incompatibility. Most likely the server is running in Python 2 mode - you cannot change it without restarting.

**Comment by vmarkovtsev** [comment]
The possible solution is to do these `export`-s in the container which is running Spark.

**Comment by zurk** [comment]
@warenlg and I did not see this error anymore. 
So, here you can find an instruction how to run Engine on the cluster with python3.
I close it.
