### ISSUE TITLE
Duplicate examples folders in repository root, no references

### ISSUE THREAD

**Issue by marnovo** [src-d/engine#331]
Didn't find in the search. ☑️ 

## Expected Behavior

1. Have just one `examples folder` inside the repository.
2. Have the examples folder linked in the readme.

## Current Behavior

1. Currently there are `_examples` and `examples`. What is the difference and why we have two?
2. Unless I really missed there seems to be links to the list of examples in the readme.

## Possible Solution

1. Unify the examples folders or clarify why/how should they be used.
2. Link on the readme file when talking about examples.

## Steps to Reproduce (for bugs)

Just open the repo on github/docs on the landing/clone the repo.

## Context

1. Trying to look at examples for the engine playground design docs.
2. Ditto

## Your Environment (for bugs)

* Version used: v0.5.1

**Comment by erizocosmico** [comment]
`_examples` is the folder required by docsrv to serve our examples, which you can find here (https://engine.sourced.tech/v0.5.3/examples/). The links don't work, though, so it's pointless to link to them from our README right now. That's an issue that should be fixed on docsrv.

The other is just the example notebook and siva files we use (or used to) for the container and testing.

We should unify the folders, though.

/cc @ajnavarro

**Comment by erizocosmico** [comment]
ping @ajnavarro

**Comment by ajnavarro** [comment]
Yes, we should unify the folders and use only one. We can use the needed by docserv and copy from there all the notebooks used on the docker container.

**Comment by marnovo** [comment]
Great, thanks!
