### ISSUE TITLE
Make tests work for macOS

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#335]
The integration tests fail to mount the tmp dir used on the containers.
Context in this comment: https://github.com/src-d/engine/pull/316#discussion_r264674572

**Comment by smacker** [comment]
In case somebody else needs to run tests on macOs before this issue is fixed. I do it like this:
```
TMPDIR=/Users/smacker/go/src/github.com/src-d/engine/tmp make test-integration
```

keep in mind `TMPDIR` must contain the absolute path!
