### ISSUE TITLE
Add global timeout to integration tests

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#338]
We need to guarantee that the integration tests cannot get stuck on our CI. The most simple fix is to add a `-timeout` flag to `go get`.

**Comment by smacker** [comment]
actually `go test` has default timeout of 10m. It's timeout per package: https://golang.org/cmd/go/#hdr-Testing_flags

taking into account that we run all integration test inside the same package `cmd` it works as global. 
So the question is are we ok with the default value?

**Comment by carlosms** [comment]
Thanks. 10m sounds reasonable. If we see it failing on travis because we add many new tests, we can change it later.
