### ISSUE TITLE
Parsing with bblfsh makes the container hang

### ISSUE THREAD

**Issue by erizocosmico** [src-d/engine#34]
When you try to parse anything with bblfsh the container hangs and cannot be used or deleted

**Comment by erizocosmico** [comment]
Been investigating this a bit and it seems that container is perfectly reachable and the content is fine. It just hangs forever doing the request to the gRPC server. Not sure why, though.

Happens also with gitbase and bblfsh-web.

**Comment by juanjux** [comment]
Adding some info from our intense debugging session on slack:

- Looks like it only happens with macOS.
- Where it fails, manually running bblfshd + client-go works.
- ... but a bblfshd spawned by srcd and then used with client-go also hangs, even if the port 9432 is exposed.

Still investigating.

**Comment by erizocosmico** [comment]
fixed
