### ISSUE TITLE
On Windows Engine apparently have some issues with indexes

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#349]
On Windows adding indexes *seems* to work as something is being written in the `C:\Users\Windows10\.srcd\gitbase\<hash>\` directory. But trying to show them using the `sql` command return an empty result. See the following gif.

![windows-engine-index-issue](https://user-images.githubusercontent.com/5599208/54605047-9803d700-4a48-11e9-93d1-d11c07ee66df.gif)

**Comment by smacker** [comment]
It's bug in gitbase. More info here: https://github.com/src-d/gitbase/issues/747

**Comment by smacker** [comment]
I just figured we most probably can fix it on our side by using docker volumes for indexes instead of binded directory.

**Comment by smacker** [comment]
we agreed to proceed with docker volumes to fix it.
