### ISSUE TITLE
srcd prune should remove gitbase indexes too

### ISSUE THREAD

**Issue by smacker** [src-d/engine#352]
Idea from https://github.com/src-d/engine/pull/351#pullrequestreview-216177409

Makes a lot of sense to me.

**Comment by dpordomingo** [comment]
Does source{d} Engine use temporary data in the host machine?
some other thing in `~/.gitbase` that should be deleted?

**Comment by carlosms** [comment]
I think we only have the `~/.srcd/gitbase` dir.
