### ISSUE TITLE
Function parse_uast_node does not work as expected

### ISSUE THREAD

**Issue by kafkasl** [src-d/engine#352]
## Expected Behavior
Using the `engine.parse_uast_node(uast)` turns a UAST bynary (obtained from the pyspark engine) into a python UAST node.

## Current Behavior
It returns a `class 'py4j.java_gateway.JavaObject` and its children can not be iterated or the members used the same way I do with nodes obtained with `babelfishclient.parse()`.

## Possible Solution
Using instead `Node.FromString(uasts.first()["uast"][0])` yields a node with type  `gopkg.in.bblfsh.sdk.v1.uast.generated_pb2.Node` with the expected behavriour.

## Steps to Reproduce (for bugs) 
```
from sourced.engine import Engine
from pyspark.sql import SparkSession

spark = SparkSession.builder\
.master("local[*]").appName("Examples")\
.getOrCreate()

engine = Engine(spark, "/repositories/siva/latest/*", "siva")
print("%d repositories successfully loaded" % (engine.repositories.count()/2))


uasts = engine.repositories.references.head_ref.commits.tree_entries.blobs\
    .classify_languages().where('lang = "Python"')\
    .extract_uasts().query_uast('//*[@roleIdentifier]')\
    .extract_tokens('result', 'tokens').select('uast')

uast = engine.parse_uast_node(uasts.first()["uast"][0])

for c in uast.children:
    print(c)
```

## Context
I was trying to get the binay UAST returned by the dataframe of the engine inside pyspark console into a usable python object (like the one that `babelfishclient.parse()` ) returns.

## Your Environment (for bugs)

* Version used: 0.5.5
* Operating System and version: linux mint 18
* Some needed resources to reproduce the problem: pyspark console (2.2.1) python (3.5.2)

**Comment by erizocosmico** [comment]
Yeah, `parse_uast_node` returns an instance of the Scala class, since it was more of a thing for testing than for outside usage. It will be removed in future releases or replaced with `Node.FromString` from the python bblfsh client.

Will update the docs with that.
