### ISSUE TITLE
commits table with filter index does not walk the full history

### ISSUE THREAD

**Issue by smola** [src-d/engine#368]
## Expected Behavior

This query should output something higher than 0 if there is any repository with more than one commit in the same reference:

```sql
SELECT COUNT(*) FROM commits WHERE index > 0
```

## Current Behavior
This works for me with local Spark + engine 0.5.5 (both `spark-shell --package` and `engine-jupyter`, both local filesystem and HDFS).

But in cluster mode (pipeline-staging cluster), it does not work:

```
scala> sc.master
res34: String = spark://[master host]:7077

scala> sc.version
res35: String = 2.2.0

scala> import tech.sourced.engine._
import tech.sourced.engine._

scala> val engine = Engine(spark, "hdfs://[hdfs namenode host]/100-siva", "siva")
engine: tech.sourced.engine.Engine = tech.sourced.engine.Engine@10db002c

scala> spark.registerUDFs

scala> print(s"${engine.getRepositories.count()} repositories successfully loaded")
149 repositories successfully loaded                             

scala> spark.sql("SELECT COUNT(*) FROM commits").show(1, false)
+--------+                                                                      
|count(1)|
+--------+
|100     |
+--------+

scala> spark.sql("SELECT COUNT(*) FROM commits WHERE index > 0").show(1, false)
+--------+                                                                      
|count(1)|
+--------+
|0       |
+--------+
```

## Possible Solution
No idea.

## Steps to Reproduce
I have not tried with other clusters so far, so I'm not sure if this fails with cluster mode in general, or with our Spark cluster in staging (Spark 2.2.0).

## Context
Trying to executing some queries with engine-jupyter + staging cluster.

## Your Environment
* Version used: Spark 2.2.0, engine 0.5.5
* Operating System and version: pipeline-staging cluster on kubernetes
* Some needed resources to reproduce the problem: I can provide access to a machine exhibiting the issue.

**Comment by erizocosmico** [comment]
Works for me. 
<img width="918" alt="screen shot 2018-04-10 at 13 55 49" src="https://user-images.githubusercontent.com/1312023/38555587-00016c5e-3cc7-11e8-965a-4c736eed44dd.png">

Can you execute this? Maybe all 100 commits have index 0.

```sql
SELECT COUNT(index), index FROM commits GROUP BY index
```

It's really weird that 149 repos amount to only 100 commits.

**Comment by ajnavarro** [comment]
@erizocosmico but the problem only occurs on a cluster execution. Did you test that on a cluster?
