### ISSUE TITLE
Test new features on windows

### ISSUE THREAD

**Issue by smacker** [src-d/engine#379]

**Comment by carlosms** [comment]
Some more details of what I can think of testing:
- [ ] sql with query as argument
- [ ] sql REPL. Also using control characters, like ctrl+R or ctrl+D
- [ ] check if the new mysql client closes https://github.com/src-d/engine/issues/257
- [ ] write index data, check that we can stop and init again, and use the index correctly
- [ ] prune after having volumes populated with index data, check that the volumes are deleted correctly

**Comment by smacker** [comment]
> sql with query as argument

works like a charm

> sql REPL

1. It works in general (you can type, execute queries, see results)
2. Arrow keys don't work
3. Search in the history (Ctrl-R) doesn't work correctly
<img width="1120" alt="Screenshot 2019-03-29 at 11 50 34" src="https://user-images.githubusercontent.com/406916/55227994-3d713480-5219-11e9-80a1-0db6a01a17e3.png">
4. Delete button doesn't work correctly
<img width="536" alt="Screenshot 2019-03-29 at 11 51 54" src="https://user-images.githubusercontent.com/406916/55228013-48c46000-5219-11e9-985a-ffa600d9f1b4.png">
5. Ctrl-D works correctly

I managed to "fix" delete button somehow once. I'm not sure what I did. But next runs of `srcd sql` had the bug again.

> check if the new mysql client closes #257

it solves the bug from that issue but there are still weird characters in some cases as described above

> write index data

index works correctly now:
<img width="824" alt="Screenshot 2019-03-29 at 11 56 43" src="https://user-images.githubusercontent.com/406916/55228275-0a7b7080-521a-11e9-8336-cfc17fb157f3.png">
<img width="1435" alt="Screenshot 2019-03-29 at 11 57 09" src="https://user-images.githubusercontent.com/406916/55228283-0ea78e00-521a-11e9-8c35-b125b97f0c16.png">
<img width="895" alt="Screenshot 2019-03-29 at 11 57 47" src="https://user-images.githubusercontent.com/406916/55228291-12d3ab80-521a-11e9-9103-c9f6db4b62a1.png">

> check that we can stop and init again, and use the index correctly

works correctly

> prune after having volumes populated with index data, check that the volumes are deleted correctly

works correctly

**Comment by smacker** [comment]
Looks like everything is ok except weird charactes. I added comment to 257 and close this one.
