### ISSUE TITLE
Can not stop a query

### ISSUE THREAD

**Issue by dpordomingo** [src-d/engine#384]
Trying to stop a query either run from mysql client, srcd sql client, or srcd sql command does not work as expected because it keeps running on background as it can be seen if querying the `PROCESSLIST`.

It works if quering and cancelling from `gitbase-web`.

using:
- docker version: 1.39
- srcd cli version: v0.11.0
- srcd daemon version: v0.11.0
- srcd/gitbase: v0.19.0
- srcd/gitbase-web: v0.6.2

**Comment by carlosms** [comment]
How are you cancelling the query exactly? `kill`, `kill connection`, `kill query`?

**Comment by dpordomingo** [comment]
I think that `Ctrl+C` should be also captured by `srcd sql` and kill the query being processed.

**Comment by smacker** [comment]
that is not how mysql clients work. Exit breaks the connection and we do it right now. Imo it's better to keep engine behavior consistent with the user's prior knowledge.

**Comment by carlosms** [comment]
can we close this one @dpordomingo?

**Comment by dpordomingo** [comment]
I still could not kill some queries, even with `kill` command from another `mysql client` from another shell tab... but could not describe the problem good enough to be fully reproducible...
So... we could close... and I'll reopen once I have more data to describe the problem.

**Comment by carlosms** [comment]
Closing, since Engine sql client works as expected. If you have any problem using `kill` it is most probably not related to Engine.
Also, take a look at this one, in case you hit a related problem: https://github.com/src-d/go-mysql-server/issues/635
