### ISSUE TITLE
commits filtering counterintuitive behaviour

### ISSUE THREAD

**Issue by zurk** [src-d/engine#396]
I use default siva files from [example directory](https://github.com/src-d/engine/tree/master/_examples/siva-files) and run next simple commands via pyspark: 

```python
>>> from sourced.engine import Engine
>>> SIVA_DIR = "/Users/k/sourced/siva-files"  # change me!
>>> engine = Engine(spark, SIVA_DIR, "siva")
>>> commits = engine.repositories.references.head_ref.commits
>>> commits.count()
7
>>> commits.filter(commits.index >=0).count()
638
>>> commits.filter(commits.index == 0).count()
7
>>> commits.filter(commits.index <= 1).count()
14
```

So, as I understand if I ask for commits, Engine gives me only commits with index 0. In case I want all commits I should do something like `commits.filter(commits.index >=0).count()`. It is counterintuitive because usually `filter` operation only filters data without adding something new. 

I think such behavior is related to performance questions and cannot suggest any solution here, so I just want to accent your attention and maybe you know a good solution for this problem.

**Comment by ajnavarro** [comment]
We changed that behavior because before for users was strange to return the complete history of a reference, that's why now we are returning only the first commit on a reference. If you need to get all the commits from a reference, use `all_reference_commits` instead of `commits`.
