### ISSUE TITLE
Docker Hub 'latest'  image doesn't point to master Dockerfile.

### ISSUE THREAD

**Issue by alejandrosame** [src-d/engine#411]
## Expected Behavior
Pulling the 'latest' image from Docker Hub  should give me the same container as building image from master branch. 

## Current Behavior
When I run the container as described in the README and starting using the example notebook provided I get the same error as reported in issue #405.

However, if I clone the project and build the image using master branch Dockerfile I stop receiving the error in issue #405.  

## Possible Solution
* Update Dockerfile used with latest tag in Docker Hub with the Dockerfile in master branch.
* Provide a different tag and update the README instructions to allow users to copy-paste

## Steps to Reproduce (for bugs)
1. docker run --name engine-jupyter --rm -it -p 8080:8080 -v $(pwd)/path/to/siva-files:/repositories --link bblfshd:bblfshd srcd/engine-jupyter
2. Open notebook on browser.
3. Executing the first cell in the notebook gives the same error as reported in issue #405

On the other hand:
1. git clone https://github.com/src-d/engine.git
2. cd engine
3. docker build -t test/engine-jupyter .
4. docker run --name engine-jupyter --rm -it -p 8080:8080 -v $(pwd)/path/to/siva-files:/repositories --link bblfshd:bblfshd test/engine-jupyter
4. Open notebook on browser.
5. Executing the first cell in the notebook doesn't give error as reported in issue #405, but leads to issue #410.

## Context
Trying to replicate steps indicated in the engine project README. Using Docker image for an out-of-the-box experience to test the engine capabilities.

## Your Environment (for bugs)
Running docker and git commands in Ubuntu 18.04.

**Comment by alejandrosame** [comment]
@campoy

**Comment by ajnavarro** [comment]
This is an intended behavior. `latest` must point to the latest engine version, not to the latest commit on master, that might be unstable.
