### ISSUE TITLE
Missing dependencies for pyspark in README

### ISSUE THREAD

**Issue by alejandrosame** [src-d/engine#412]
## Expected Behavior
I expect to be able to follow the README instructions in order and be able to execute the examples successfully.

## Current Behavior
When launching pyspark and trying to import engine, I get a ```ModuleNotFoundError: No module named 'bblfsh'``` error.

## Possible Solution
Add somewhere in the README that before executing pyspark users need to execute ```sudo apt-get install curl g++ libxml2-dev``` and ```pip install bblfsh```.

## Steps to Reproduce (for bugs)
1. ```pyspark --packages "tech.sourced:engine:0.6.4"```
2. ```>>> from sourced.engine import Engine```

After the import, the user receives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alejandro/.local/lib/python3.6/site-packages/sourced/engine/__init__.py", line 3, in <module>
    from bblfsh.sdkversion import VERSION
ModuleNotFoundError: No module named 'bblfsh'

```

## Context
I was following the REDME to check installation from scratch.

## Your Environment (for bugs)
Executing the README instructions on Ubuntu 18.04.

**Comment by alejandrosame** [comment]
Maybe I'm doing something wrong, but I still need to install bblfsh through pip to make it work.

With ```pyspark --packages "tech.sourced:engine:0.6.4"```:
```
>>> jars = [y for (x, y) in sc.getConf().getAll() if x == 'spark.jars']
>>> print([x.split("/")[-1] for x in jars[0].split(",") if 'sourced' in x or 'bblfsh' in x])
['tech.sourced_engine-0.6.4.jar', 'tech.sourced_siva-java-0.1.3.jar', 'org.bblfsh_bblfsh-client-1.8.2.jar', 'tech.sourced_enry-java-1.6.3.jar']

>>> from sourced.engine import Engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alejandro/.local/lib/python3.6/site-packages/sourced/engine/__init__.py", line 3, in <module>
    from bblfsh.sdkversion import VERSION
ModuleNotFoundError: No module named 'bblfsh'
```

And with ```pyspark --packages "tech.sourced:engine:0.7.0"```:
```
>>> jars = [y for (x, y) in sc.getConf().getAll() if x == 'spark.jars']
>>> print([x.split("/")[-1] for x in jars[0].split(",") if 'sourced' in x or 'bblfsh' in x])
['tech.sourced_engine-0.7.0.jar', 'tech.sourced_siva-java-0.1.3.jar', 'org.bblfsh_bblfsh-client-1.9.1.jar', 'tech.sourced_enry-java-1.6.3.jar']
>>> from sourced.engine import Engine
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alejandro/.local/lib/python3.6/site-packages/sourced/engine/__init__.py", line 3, in <module>
    from bblfsh.sdkversion import VERSION
ModuleNotFoundError: No module named 'bblfsh'
```

**Comment by ajnavarro** [comment]
Thanks for the report @alejandrosame !, We are having a look.

**Comment by erizocosmico** [comment]
Did you install the latest `sourced-engine` python package? It should already install bblfsh without requiring you to manually install it.

**Comment by alejandrosame** [comment]
@erizocosmico, @ajnavarro Indeed that worked! Thank you!

**Comment by erizocosmico** [comment]
Great! I will add more detailed requirements for python to the README, anyway.
