### ISSUE TITLE
Build and test process leave the repository in dirty state for git describe

### ISSUE THREAD

**Issue by smola** [src-d/engine#413]
## Expected Behavior
Docker image: srcd/engine-jupyter:dev-9b1c91a

## Current Behavior
srcd/engine-jupyter:dev-9b1c91a-dirty
Note the `-dirty` suffix.

## Possible Solution
Check that, after building engine `git describe` returns a string without `-dirty` suffix.
If it doesn't, check `git status`. Fix may involve adding stuff to `.gitignore`, changing the path something uses for tests or builds, etc.

## Steps to Reproduce (for bugs)
Build, test and run `git describe`.

## Context
This is, mainly, a cosmetic change. Although it may hide other bugs.

**Comment by erizocosmico** [comment]
I've done:

```
make build
make test
git status --porcelain
```

and can't reproduce this.

AFAIK, [we use `git status --porcelain`](https://github.com/src-d/engine/blob/master/Makefile#L57), not `git describe`.

What's the output that commands gives for you?

**Comment by smola** [comment]
Note that this issue was an observation directly on Docker Hub, so I didn't reproduce it locally yet: https://hub.docker.com/r/srcd/engine-jupyter/tags/

**Comment by erizocosmico** [comment]
Ah, ok, I thought you meant locally. Will take a look at this again
