### ISSUE TITLE
SIGSEGV on `srcd sql` on macOS

### ISSUE THREAD

**Issue by mumoshu** [src-d/engine#415]
With srcd v0.12.0, I'm unable to run any srcd command that requires cli-daemon due to SIGSEGV:

```
$ srcd init

$ srcd sql
INFO[0000] installing "mysql:8"                         
INFO[0005] this is taking a while, if this is the first time you launch sql client, it might take a few more minutes while we install all the required images 
INFO[0017] installed "mysql:8"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15b5fe5]

goroutine 84 [running]:
github.com/src-d/engine/cmd/srcd/cmd.pingDB.func1(0x18088c0, 0xc00000e0d0, 0x1803f60, 0xc000068120, 0xc00033a540)
	/home/travis/gopath/src/github.com/src-d/engine/cmd/srcd/cmd/sql.go:155 +0xd5
created by github.com/src-d/engine/cmd/srcd/cmd.pingDB
	/home/travis/gopath/src/github.com/src-d/engine/cmd/srcd/cmd/sql.go:149 +0x111
```

Reading some code around the line:

https://github.com/src-d/engine/blob/f969337fa5e4f19191539be992a604d098d2f908/cmd/srcd/cmd/sql.go#L155

And reading logs from various srcd command, what seems suspicious to me is that, `srcd` is trying to connect `0.0.0.0:4242`, which won't work as my srcd should be running in my VirtualBox VM:

```
$ srcd version
srcd cli version: v0.12.0
docker version: 1.38
Usage:
  srcd version [flags]

Flags:
  -h, --help   help for version

Global Flags:
      --config string   config file (default is $HOME/.srcd/config.yml)
  -v, --verbose         if true, log all of the things

could not get daemon version: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:4242: connect: connection refused"
```

Should this be a kind of bug, or I have made any configuration mistake?

**Comment by carlosms** [comment]
You mentioned Virtualbox. Are you using the Docker Toolbox environment? For macOS and windows we only support Docker Desktop.

**Comment by mumoshu** [comment]
Thanks! I missed that. Will try once again with Docker Destop and report
back if something still don't work.

2019年4月8日(月) 18:10 Carlos Martín <notifications@github.com>:
