### ISSUE TITLE
Handle missing docker desktop or docker toolbox installation.

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#417]
In #415 instead of failing with a panic, srcd should have been able to detect the required docker desktop installation, and fail gracefully.

Scenarios I can think of:
- Docker version is lower than we require
- Docker toolbox is found
- Docker is missing completely

**Comment by se7entyse7en** [comment]
> Docker version is lower than we require

Do we want to asses the minimum version we require and check for that hardcoded value or do we want to also add some kind of testing maybe by forcing a different docker api version?

**Comment by se7entyse7en** [comment]
I actually tried replacing all occurrences in `docker.go` of `client.NewClientWithOpts(client.WithVersion("1.18"))` just to give it a try and the integration tests passed. 1.18 is the oldest one listed [here](https://docs.docker.com/develop/sdk/#view-the-api-reference).

**Comment by smacker** [comment]
moby lib already checks API version and returns an error if docker server is too old.
I saw it with my docker when updated the lib to master. ([v1.40](https://github.com/moby/moby/blob/master/api/common.go#L6))
I'm not sure what `client.WithVersion` does and did you test it correctly or not but consistency mode was introduced after 1.18 for sure and we rely on it.

**Comment by se7entyse7en** [comment]
> moby lib already checks API version and returns an error if docker server is too old.

**Comment by se7entyse7en** [comment]
@smacker I've just tried to change with `client.NewClientWithOpts(client.WithVersion("1.11"))` and all the tests fail with:

`Error response from daemon: client version 1.11 is too old. Minimum supported API version is 1.12, please upgrade your client to a newer version.`

So this means that `client.WithVerson` actually works.

This also mean that all the newer features simply becomes noop. I manually tried a sample query (`Top languages by repository count`) with api version `1.12` and `1.38`. It works with both version, but with `1.12` it took ~9s and with `1.38` it took ~1.5s.

By running `docker version` on my local machine the output is:

<img width="335" alt="Screenshot 2019-04-09 at 10 25 59" src="https://user-images.githubusercontent.com/5599208/55784977-efc6b880-5ab1-11e9-80f2-f2e0f4383601.png">

So it seems that from the minimum version everything works, but it may not work *as good as expected*. This is aligned to what is stated in the [documentation](https://docs.docker.com/develop/sdk/#view-the-api-reference):

> _A new version of the API is released when new features are added. The Docker API is backward-compatible, so you do not need to update code that uses the API unless you need to take advantage of new features._

Hence I see two options:
1. we just require that everything simply works, so we could just eventually wrap the docker error message,
2. we choose a minimum version that we know it makes Engines works _as we expect_. In our case it could be `1.28` which is the first version with support to mount consistency.

**Comment by se7entyse7en** [comment]
As discussed [here](https://github.com/src-d/minutes/pull/543), we assume that the user is running the latest version of Docker and just let the SDK check for API incompatibility. We check then for:
- Docker present and running,
- Docker Toolbox instead of Docker Desktop.
