### ISSUE TITLE
Update bblfshd to v2.12.1

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#435]
New release: https://github.com/bblfsh/bblfshd/releases/tag/v2.12.1

**Comment by se7entyse7en** [comment]
Closed by #437.

**Comment by carlosms** [comment]
Not really, the bblfshd component is set in here https://github.com/src-d/engine/blob/master/components/components.go#L111

**Comment by se7entyse7en** [comment]
🤦‍♂️ sorry, didn't notice it.

But now I'm wondering whether these two bumps (component image and library) should be done together. I mean what would have happened if the not yet bumped version of the component was not compatible with the newly bumped version of the library? Do we assume thanks to `semver` that until @src-d/language-analysis doesn't change the major version, then a newer version of the package is compatible with an older version of the component image?

Even if most probably the  integration tests would have failed, there could be some unexplored cases.

**Comment by smacker** [comment]
LA team maintains compatibility very well. I can't remember even one case when a client and bblfshd were incompatible with each other. (except migration to uast v2 of course that requires bblfshd that supports v2)

**Comment by se7entyse7en** [comment]
Okay! thanks!
