### ISSUE TITLE
Tagging the latest built image also with `dev-latest`

### ISSUE THREAD

**Issue by se7entyse7en** [src-d/engine#436]
Currently when the daemon image is built using `make docker-build`, the image is tagged with `dev-<hash>-dirty`. By default when I run:
```
go run ./cmd/srcd/main.go init
```
[The version of the image used for the daemon is `latest` as the `cliVersion` is `dev` by default](https://github.com/src-d/engine/blob/master/docker/dockerhub.go#L18). I almost always forget about this expecting the daemon to be running with the latest image I built.

What I do now is to run:
```
go run -ldflags "-X main.version=dev-<hash>-dirty" ./cmd/srcd/main.go init
```
using the write image tag, or I manually tag the latest image I built as "latest". Both solutions are not optimal IMO. What about changing the default `cliVersion` to `dev-latest` and tag the image built using `make docker-build` accordingly (without replacing the current tag, but just adding this new one)?

Are you perhaps using another simpler approach that I'm missing?

**Comment by carlosms** [comment]
You can also do 
`VERSION=latest make docker-build`

**Comment by smacker** [comment]
I usually built it with `cd cmd/srcd-server/; make`. It creates an image with `latest` tag.

**Comment by carlosms** [comment]
Closing, use case is already supported with `VERSION`.
