### ISSUE TITLE
Question: user name and password for gitbase?

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#445]
It is not clear from the README which username and password I should use if I want to connect to gitbase using an external mysql connector. Actually, which DB name, too.

**Comment by vmarkovtsev** [comment]
Answering myself after studying the code:

* username `root`
* no password
* db name `gitbase`

**Comment by carlosms** [comment]
Thank you. We are exposing the port to make this possible, so we should add the credentials it to the docs.
