### ISSUE TITLE
Error attempting to open web parse/SQL

### ISSUE THREAD

**Issue by forstmeier** [src-d/engine#469]
## Description
I'm attempting to run the srcd daemon but am getting errors while trying to execute some commands. Running `sudo srcd web sql` or `sudo srcd web parse` both generate the following error:
```
You need to enable JavaScript to run this app.
```

No website renders and I'm unable to see anything on the `http://localhost:8080` URL. As a side note, sometimes running `sudo srcd init` results in a failure as well.

I'm running this on Ubuntu.

**Comment by carlosms** [comment]
Hi,

What browser are you using? Is it possible some extension is causing this problem? Do you have any error messages in the browser developer console?

**Comment by se7entyse7en** [comment]
AFAIU no browser actually opens and that message is being printed in the terminal, am I correct? Could it be possible that the browser it's trying to open is a headless browser?

**Comment by forstmeier** [comment]
@se7entyse7en It was me being stupid: the browser wasn't opening automatically I just had to manually go to http://localhost:8080 after entering the command in order to make it work. Thanks!
