### ISSUE TITLE
"Contribution" link broken

### ISSUE THREAD

**Issue by gomesfernanda** [src-d/engine#49]
When clicking "Please refer to **our contribution guide**" on [Contribution section](https://github.com/src-d/engine/#contributing), the link is broken.

Link: https://github.com/src-d/engine/blob/master/CONTRIBUTING.md

**Comment by eiso** [comment]
@campoy we need to add a proper CONTRIBUTING.md. For now I'll commit our usual one from [here](https://github.com/src-d/guide/blob/master/engineering/documents/CONTRIBUTING.md) but we should personalize it to the project.
