### ISSUE TITLE
`web sql` starting page misses images, confusing behavior

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#57]
I run `srcd web sql` and get:

![image](https://user-images.githubusercontent.com/2793551/46003747-8bae4b00-c0b1-11e8-951c-ab9cd6751484.png)

Also:

![image](https://user-images.githubusercontent.com/2793551/46003812-a54f9280-c0b1-11e8-9cfb-d8726268b77a.png)

The images are missing. When I hit `Ctrl-R`, I get straight to "Gitbase Web"  interface. No more "sign in" buttons.

Tagging @bzz

**Comment by campoy** [comment]
This is normal and due to the local storage (from a different web) being attached to the URL localhost:8080.

This shouldn't impact other developers as their URLs wouldn't be the same.

**Comment by vmarkovtsev** [comment]
Seeing broken web pages is not normal @campoy

Also don't get what you mean about other developers...

**Comment by campoy** [comment]
ping @vmarkovtsev

**Comment by vmarkovtsev** [comment]
@campoy That command lists the current directory as it should.

I will run `srcd web sql` on a clean environment once I find time.

**Comment by carlosms** [comment]
That cached content comes from [code-annotation](https://github.com/src-d/code-annotation), and is not related to engine.

Some context: If I'm not mistaken that service worker cache is/was a default for create-react-app (react project bootstrap utility). If all goes well things load faster. If you reuse a url, the only harm it does is that you will need to refresh once more to see the changes.

Side note: this is related to https://github.com/src-d/feature-idea/issues/83

**Comment by smacker** [comment]
I believe we can close this issue because it has nothing to do with this project.

Any application can install a service worker in the browser on 8080 port. (for our src-d frontend projects we are disabling service workers now)

There is no way to avoid it.  A user must hard-refresh to remove cache. Though we might change ports to less common in the future but to avoid a port collision, not this problem.

**Comment by vmarkovtsev** [comment]
I see, thanks for explaining.
