### ISSUE TITLE
Babelfish image version is not checked

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#58]
![image](https://user-images.githubusercontent.com/2793551/46009030-a5a25a80-c0be-11e8-9d7d-beedc08f688e.png)

@ajnavarro says: Babelfish image is too old.
I think the same because `SupportedLanguages()` API has been added since ages.

**Comment by vmarkovtsev** [comment]
I found the real cause. Engine does not check the preinstalled bblfshd version so was using the one already pulled on my system. `docker pull bblfsh/bblfshd:latest` fixed the problem. Changing the issue title.

**Comment by campoy** [comment]
I had a similar issue where bblfsh would not start after a `docker system purge -a -f` because it wouldn't automatically pull the image at all.

@erizocosmico might be able to help with this?
