### ISSUE TITLE
`kill` does not remove srcd-cli-network

### ISSUE THREAD

**Issue by vmarkovtsev** [src-d/engine#62]
Regardless of whether `srcd kill` is supposed to nuke everything or just the container instances, it misses to remove `srcd-cli-network` network.

**Comment by campoy** [comment]
I wonder if `kill` is a good name then, since we're also removing things ... I'd argue renaming the command to `srcd purge` and make it be similar to `docker purge`.

**Comment by smacker** [comment]
To be more consistent with docker I think it shouldn't be just renamed but we need to split this command to 2.

- `srcd kill` stops (kills) containers same as `docker kill` does.
- `srcd prune` removes everything except images, with `-a` flag removes images too. Similar to what `docker system prune` does.
