### ISSUE TITLE
Handle releases correctly

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#64]
If we create a new tag defining a version on the spark-api repository, we should:
- Execute all the tests
- Generate a `uber-jar` using `sbt assembly`
- Generate a new container version including the new `uber-jar`
- Upload assembly jar to spark packages
- Upload python code to pypi

**Comment by erizocosmico** [comment]
Isn't this already done?

**Comment by ajnavarro** [comment]
Not yet. Actually we have docker container release and pypi release. We miss a jar release on maven central.

**Comment by bzz** [comment]
Shall we use [the same way](https://github.com/bblfsh/client-scala/blob/master/build.sbt#L41) as bblfsh/client-scala to add an SBT build target for publishing releases on Sonatype ?
