### ISSUE TITLE
Make logs more explicit than "creating it now"

### ISSUE THREAD

**Issue by carlosms** [src-d/engine#68]
It's a minor usability thing, but in this log:

```
$ ./srcd init
INFO[0000] starting daemon with working directory: /home/cmartin/engine/engine_linux_amd64 
INFO[0000] installing "srcd/cli-daemon:latest"          
INFO[0005] installed "srcd/cli-daemon:latest"           
INFO[0007] couldn't find network srcd-cli-network: Error: No such network: srcd-cli-network 
INFO[0007] creating it now  
```
Is "it" the missing network, or is "it" the `daemon` mentioned in the first log line?
We could make the last message more explicit to assure that we are taking care of the missing network error.

**Comment by smola** [comment]
I've just stumbled on the same thing. I would propose the following:

- First line moved to `DEBUG` level, since the `Error: No such network: srcd-cli-network` stuff is just too much.
- Second line rephrased to `creating srcd-cli-network docker network` (or something along these lines).
