### ISSUE TITLE
Engine unable to remove images with `srcd kill`

### ISSUE THREAD

**Issue by marnovo** [src-d/engine#76]
Expectation for [`srcd kill` command](https://docs.sourced.tech/engine/learn-more/commands#srcd-kill):
> Removes all containers, docker images and docker volumes used by the source{d} engine.

Reality:

[From Slack](https://src-d.slack.com/archives/C7UDG0GP6/p1539289002000100) by @kuba--:
> After I stoped pilosa container I tried `srcd kill` and it failed because we could not stop all containers (I still had bblfsh and daemon running). I think we should stop as many containers as we can.

**Comment by kuba--** [comment]
Duplicates https://github.com/src-d/engine/issues/74
