### ISSUE TITLE
Proposal: use fixed versions for dependencies instead of latest

### ISSUE THREAD

**Issue by smacker** [src-d/engine#83]
We do break backward compatibility from time to time.

Gibase should have correct version of bblfshd, gitbase-web should have correct version of gitbase and so on.

Cons: We will have to manually update versions from time to time
Pros: Engine wouldn't get broken when all latests aren't compatible with each other and avoid problems like #58 #67 #65

@campoy

**Comment by carlosms** [comment]
:+1: I completely agree, we should make sure it works as expected with the versions we test.

**Comment by campoy** [comment]
Yes, please.
Again, this is a topic that will be discussed in tomorrow's meeting.
