### ISSUE TITLE
Remove driver management commands

### ISSUE THREAD

**Issue by smacker** [src-d/engine#85]
From the docs:

> All of the subcomands of srcd parse drivers provide management for the language drivers installed on bblfsh.

but it's marked as TBD.

We need to test it and update docs if everything works.

**Comment by smacker** [comment]
I agree with you in general but I think ability to install experimental or 3rd-party drivers may be handy too. 

@campoy

**Comment by campoy** [comment]
I think that not having the ability to install experimental stuff on the engine is totally fine.
The whole idea behind the engine is to provide an easy way to get started for anyone.

We will discuss this and more on a meeting tomorrow, I added you (@carlosms) to the meeting.
It'd be great if you can make it, I think your opinion will help us better decide what can be done.

**Comment by smacker** [comment]
I updated the issue title. It makes much more sense now as we don't install drivers directly anymore but use `bblfsh-drivers` image.
