### ISSUE TITLE
Change the actual notebook to make good examples using enry and bblfsh.

### ISSUE THREAD

**Issue by ajnavarro** [src-d/engine#92]
Also try to make some aggregation (like top 10 languages in all the repositories of the subset)

**Comment by bzz** [comment]
Is there anything else to be done?

https://github.com/src-d/spark-api/blob/master/examples/notebooks/Example.ipynb seems quite good

**Comment by erizocosmico** [comment]
Don’t think so, examples seem fine now
On Wed, 18 Oct 2017 at 18:37, Alexander <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there anything else to be done?

https://github.com/src-d/spark-api/blob/master/examples/notebooks/Example.ipynb seems quite good

**Comment by bzz** [comment]
Nice! Closing it for now then
