### ISSUE TITLE
Make sure cli is compatible with server image

### ISSUE THREAD

**Issue by smacker** [src-d/engine#92]
We have 2 options:
1. always keep backward compatibility but it would cause a lot more work and testing
2. cli can use sem ver to download only the latest compatible version instead of the latest

**Comment by smacker** [comment]
we currently have a change that breaks old cli: https://github.com/src-d/engine/pull/90

I would really prefer to implement option 2. But it would require to break old cli at least once.
@campoy are you okay with that?

**Comment by campoy** [comment]
Solution 2 is the way to go.

Feel free to break the old CLI once, no problem.
Just add a check asking the user to download the latest binary.
